# Generated by scripts/generate-qc-actions.mjs. Do not edit by hand.
from __future__ import annotations

from typing import Any


class GeneratedQcTools:
    def reconnect_device(
        self,
        confirm_risky_operation: bool,
    ) -> Any:
        """Reconnect the native Quad Cortex transport after explicit confirmation."""
        return self._invoke_generated_action("reconnect_device", locals())

    def reset_device_session(
        self,
        confirm_risky_operation: bool,
    ) -> Any:
        """Reset and re-synchronize the native Quad Cortex communication session after explicit confirmation."""
        return self._invoke_generated_action("reset_device_session", locals())

    def disconnect_device(
        self,
        confirm_risky_operation: bool,
    ) -> Any:
        """Close the native Quad Cortex transport after explicit confirmation."""
        return self._invoke_generated_action("disconnect_device", locals())

    def get_current_preset(
        self,

    ) -> Any:
        """Read the authoritative current preset, scene, tempo and Grid state."""
        return self._invoke_generated_action("get_current_preset", locals())

    def get_state_events(
        self,
        after_sequence: int,
        limit: int,
    ) -> Any:
        """Read native state frames after a sequence cursor."""
        return self._invoke_generated_action("get_state_events", locals())

    def get_tempo_clock(
        self,

    ) -> Any:
        """Read the most recent native metronome beat, bar and tick state."""
        return self._invoke_generated_action("get_tempo_clock", locals())

    def get_block_details(
        self,
        row: int,
        column: int,
        expected_preset_name: str,
    ) -> Any:
        """Read live parameters for one occupied Grid block, splitter, or mixer."""
        return self._invoke_generated_action("get_block_details", locals())

    def get_lane_control_details(
        self,
        row: int,
        control: str,
        expected_preset_name: str,
    ) -> Any:
        """Read the Input Gate or Lane Output parameters attached to a signal row."""
        return self._invoke_generated_action("get_lane_control_details", locals())

    def list_models(
        self,
        query: str | None,
    ) -> Any:
        """Find installed block models and their numeric IDs."""
        return self._invoke_generated_action("list_models", locals())

    def list_presets(
        self,
        refresh: bool,
        setlist_key: str | None,
    ) -> Any:
        """List presets in a setlist, optionally refreshing the device index."""
        return self._invoke_generated_action("list_presets", locals())

    def list_preset_folders(
        self,
        refresh: bool,
    ) -> Any:
        """List preset folders and setlists, optionally refreshing the device index."""
        return self._invoke_generated_action("list_preset_folders", locals())

    def list_preset_slots(
        self,

    ) -> Any:
        """List preset destinations and their occupancy before a persistent write."""
        return self._invoke_generated_action("list_preset_slots", locals())

    def get_master_volume(
        self,

    ) -> Any:
        """Read the authoritative master output volume."""
        return self._invoke_generated_action("get_master_volume", locals())

    def get_device_identity(
        self,

    ) -> Any:
        """Read the connected Quad Cortex serial number, firmware version, type and custom name."""
        return self._invoke_generated_action("get_device_identity", locals())

    def get_inhibited_modules(
        self,

    ) -> Any:
        """Read the authoritative Global Gate and Global EQ inhibition state."""
        return self._invoke_generated_action("get_inhibited_modules", locals())

    def get_tuner_settings(
        self,

    ) -> Any:
        """Read the tuner input, mute preference, and reference pitch without changing or engaging the tuner."""
        return self._invoke_generated_action("get_tuner_settings", locals())

    def set_tuner_input(
        self,
        input_port_id: int,
        confirm_tuner_activation: bool,
        confirm_risky_operation: bool,
    ) -> Any:
        """Choose the tuner input. This invisibly engages the tuner and can silence the rig if its mute preference is enabled."""
        return self._invoke_generated_action("set_tuner_input", locals())

    def set_tuner_mute(
        self,
        muted: bool,
        confirm_tuner_activation: bool,
        confirm_risky_operation: bool,
    ) -> Any:
        """Change mute-while-tuning. This invisibly engages the tuner; enabling mute immediately silences all outputs."""
        return self._invoke_generated_action("set_tuner_mute", locals())

    def restore_tuner_audio(
        self,
        confirm_preference_reset: bool,
        confirm_risky_operation: bool,
    ) -> Any:
        """Restore audio after a host tuner write by clearing the persistent mute-while-tuning preference."""
        return self._invoke_generated_action("restore_tuner_audio", locals())

    def set_tuner_reference(
        self,
        reference_offset_hz: float,
        confirm_tuner_activation: bool,
        confirm_risky_operation: bool,
    ) -> Any:
        """Set tuner reference as an Hz offset from 440. This invisibly engages the tuner."""
        return self._invoke_generated_action("set_tuner_reference", locals())

    def get_preset_screenshot(
        self,
        folder_name: str,
        position: int,
        is_factory: bool,
    ) -> Any:
        """Read the PNG thumbnail stored for a preset."""
        return self._invoke_generated_action("get_preset_screenshot", locals())

    def capture_screen(
        self,

    ) -> Any:
        """Capture the current Quad Cortex touchscreen as a PNG image."""
        return self._invoke_generated_action("capture_screen", locals())

    def preview_parameter(
        self,
        row: int,
        column: int,
        parameter_index: int,
        value: float,
        expected_value: float,
        expected_scene: int,
        expected_preset_name: str,
    ) -> Any:
        """Preview a block, splitter, or mixer parameter value without waiting for device verification."""
        return self._invoke_generated_action("preview_parameter", locals())

    def preview_lane_control_parameter(
        self,
        row: int,
        control: str,
        parameter_index: int,
        value: float,
        expected_value: float,
        expected_preset_name: str,
    ) -> Any:
        """Preview an Input Gate or Lane Output parameter without waiting for device verification."""
        return self._invoke_generated_action("preview_lane_control_parameter", locals())

    def create_device_backup(
        self,
        name: str,
        confirm_persistent_write: bool,
    ) -> Any:
        """Create a complete local device backup after explicit confirmation."""
        return self._invoke_generated_action("create_device_backup", locals())

    def set_device_name(
        self,
        name: str,
        confirm_persistent_write: bool,
    ) -> Any:
        """Change the Quad Cortex custom name after explicit confirmation."""
        return self._invoke_generated_action("set_device_name", locals())

    def undo_device(
        self,
        confirm_risky_operation: bool,
    ) -> Any:
        """Undo the most recent device edit after explicit confirmation."""
        return self._invoke_generated_action("undo_device", locals())

    def redo_device(
        self,
        confirm_risky_operation: bool,
    ) -> Any:
        """Redo the most recently undone device edit after explicit confirmation."""
        return self._invoke_generated_action("redo_device", locals())

    def tap_screen(
        self,
        x: int,
        y: int,
        confirm_risky_operation: bool,
    ) -> Any:
        """Tap an exact touchscreen pixel after reviewing a fresh screen capture and explicitly confirming the action."""
        return self._invoke_generated_action("tap_screen", locals())

    def select_scene(
        self,
        scene: int,
        expected_preset_name: str,
    ) -> Any:
        """Immediately select a performance scene, numbered 0 through 7."""
        return self._invoke_generated_action("select_scene", locals())

    def copy_scene(
        self,
        from_scene: int,
        to_scene: int,
        swap: bool,
        expected_preset_name: str,
    ) -> Any:
        """Copy or swap two scenes in the current preset and verify the resulting scene state."""
        return self._invoke_generated_action("copy_scene", locals())

    def set_scene_label(
        self,
        scene: int,
        label: str | None,
        expected_preset_name: str,
    ) -> Any:
        """Set or clear the label of one scene in the current preset."""
        return self._invoke_generated_action("set_scene_label", locals())

    def set_scene_color(
        self,
        scene: int,
        color: int,
        expected_preset_name: str,
    ) -> Any:
        """Set the display color of one scene in the current preset."""
        return self._invoke_generated_action("set_scene_color", locals())

    def press_footswitch(
        self,
        index: int,
        expected_mode: str,
        expected_preset_name: str,
    ) -> Any:
        """Press a physical Quad Cortex footswitch by its stable hardware index."""
        return self._invoke_generated_action("press_footswitch", locals())

    def tap_tempo(
        self,
        expected_mode: str,
        expected_preset_name: str,
    ) -> Any:
        """Tap the dedicated Quad Cortex tempo control through its official MIDI command."""
        return self._invoke_generated_action("tap_tempo", locals())

    def navigate_bank(
        self,
        direction: int,
        expected_preset_name: str,
        expected_position: int,
    ) -> Any:
        """Immediately navigate one performance bank down (-1) or up (1)."""
        return self._invoke_generated_action("navigate_bank", locals())

    def show_tuner(
        self,
        shown: bool,
    ) -> Any:
        """Show or hide the tuner."""
        return self._invoke_generated_action("show_tuner", locals())

    def show_gig_view(
        self,
        shown: bool,
    ) -> Any:
        """Show or hide Gig View."""
        return self._invoke_generated_action("show_gig_view", locals())

    def select_mode_slot(
        self,
        slot: int,
        expected_preset_name: str,
    ) -> Any:
        """Select device-configured performance Mode Slot A, B, or C."""
        return self._invoke_generated_action("select_mode_slot", locals())

    def set_master_volume(
        self,
        value: int,
        expected_value: int,
        confirm_risky_operation: bool,
    ) -> Any:
        """Set master output volume after explicit user confirmation and stale-value validation."""
        return self._invoke_generated_action("set_master_volume", locals())

    def recall_preset(
        self,
        setlist_key: str,
        position: int,
        expected_preset_name: str,
        expected_position: int,
        expected_setlist_key: str,
    ) -> Any:
        """Immediately recall a preset by setlist key and position, guarded by the currently active setlist, preset name, and position."""
        return self._invoke_generated_action("recall_preset", locals())

    def reload_preset(
        self,
        expected_preset_name: str,
        expected_position: int,
        confirm_risky_operation: bool,
    ) -> Any:
        """Discard unsaved edits and reload the active preset after explicit host confirmation."""
        return self._invoke_generated_action("reload_preset", locals())

    def set_tempo(
        self,
        bpm: int,
        expected_tempo: int,
        expected_preset_name: str,
    ) -> Any:
        """Immediately set performance tempo from 40 through 240 BPM."""
        return self._invoke_generated_action("set_tempo", locals())

    def set_bypass(
        self,
        row: int,
        column: int,
        desired_bypassed: bool,
        expected_bypassed: bool,
        expected_scene: int,
        expected_preset_name: str,
    ) -> Any:
        """Immediately enable or bypass one Grid block and verify device readback."""
        return self._invoke_generated_action("set_bypass", locals())

    def set_parameter(
        self,
        row: int,
        column: int,
        parameter_index: int,
        value: float,
        expected_value: float,
        expected_scene: int,
        expected_preset_name: str,
    ) -> Any:
        """Immediately set a writable block, splitter, or mixer parameter and verify it."""
        return self._invoke_generated_action("set_parameter", locals())

    def set_parameter_scene_mode(
        self,
        row: int,
        column: int,
        parameter_index: int,
        enabled: bool,
        expected_preset_name: str,
    ) -> Any:
        """Enable or disable per-scene storage for a block, splitter, or mixer parameter and verify device readback."""
        return self._invoke_generated_action("set_parameter_scene_mode", locals())

    def set_parameter_expression(
        self,
        row: int,
        column: int,
        parameter_index: int,
        pedal: int,
        minimum: float,
        maximum: float,
        expected_preset_name: str,
    ) -> Any:
        """Assign EXP 1 or EXP 2 to a block, splitter, or mixer parameter, or clear it with pedal 0, preserving the requested heel and toe range."""
        return self._invoke_generated_action("set_parameter_expression", locals())

    def set_lane_control_parameter(
        self,
        row: int,
        control: str,
        parameter_index: int,
        value: float,
        expected_value: float,
        expected_preset_name: str,
    ) -> Any:
        """Set an Input Gate or Lane Output parameter with stale-value and preset guards."""
        return self._invoke_generated_action("set_lane_control_parameter", locals())

    def set_lane_control_scene_mode(
        self,
        row: int,
        control: str,
        parameter_index: int,
        enabled: bool,
        expected_preset_name: str,
    ) -> Any:
        """Enable or disable per-scene storage for an Input Gate or Lane Output parameter and verify readback."""
        return self._invoke_generated_action("set_lane_control_scene_mode", locals())

    def set_expression_bypass(
        self,
        row: int,
        column: int,
        pedal: int,
        mode: int,
        invert: bool,
        delay_ms: int,
        latch_emulation: bool,
        expected_preset_name: str,
    ) -> Any:
        """Assign EXP 1 or EXP 2 to a block bypass with the QC switch mode, inversion, delay and latch-emulation settings."""
        return self._invoke_generated_action("set_expression_bypass", locals())

    def move_block(
        self,
        row: int,
        from_column: int,
        to_column: int,
        expected_model_id: int,
        expected_preset_name: str,
    ) -> Any:
        """Move an existing Grid block to an empty column in the same row with model and preset guards."""
        return self._invoke_generated_action("move_block", locals())

    def add_block(
        self,
        row: int,
        column: int,
        model_id: int,
        expected_preset_name: str,
    ) -> Any:
        """Add an installed model to an empty Grid cell and verify the resulting block."""
        return self._invoke_generated_action("add_block", locals())

    def remove_block(
        self,
        row: int,
        column: int,
        expected_model_id: int,
        expected_preset_name: str,
    ) -> Any:
        """Remove a Grid block after validating its model and active preset."""
        return self._invoke_generated_action("remove_block", locals())

    def set_block_footswitch(
        self,
        row: int,
        column: int,
        footswitch: int | None,
        expected_footswitch: int | None,
        expected_model_id: int,
        expected_preset_name: str,
    ) -> Any:
        """Assign or clear a Grid block footswitch with preset, model and assignment guards."""
        return self._invoke_generated_action("set_block_footswitch", locals())

    def set_stomp_momentary(
        self,
        footswitch: int,
        momentary: bool,
        expected_preset_name: str,
    ) -> Any:
        """Set a single-block STOMP footswitch to momentary or latching behavior and verify device readback."""
        return self._invoke_generated_action("set_stomp_momentary", locals())

    def set_stomp_label(
        self,
        footswitch: int,
        label: str,
        expected_preset_name: str,
    ) -> Any:
        """Set the visible label of a STOMP footswitch using the device's correct single- or multi-assignment storage."""
        return self._invoke_generated_action("set_stomp_label", locals())

    def set_midi_out(
        self,
        source: int,
        messages: list[dict[str, int]],
        expected_preset_name: str,
    ) -> Any:
        """Replace up to 12 MIDI Out messages for a footswitch or expression-pedal source in the current preset."""
        return self._invoke_generated_action("set_midi_out", locals())

    def set_preset_load_midi_out(
        self,
        messages: list[dict[str, int]],
        expected_preset_name: str,
    ) -> Any:
        """Replace the MIDI Out messages sent when the current preset loads."""
        return self._invoke_generated_action("set_preset_load_midi_out", locals())

    def set_chain_input(
        self,
        row: int,
        input_id: int,
        expected_input_id: int,
        expected_preset_name: str,
    ) -> Any:
        """Change a signal-row input after validating the current route and preset."""
        return self._invoke_generated_action("set_chain_input", locals())

    def set_chain_output(
        self,
        row: int,
        output_id: int,
        expected_output_id: int,
        expected_preset_name: str,
    ) -> Any:
        """Change a signal-row output after validating the current route and preset."""
        return self._invoke_generated_action("set_chain_output", locals())

    def set_chain_split(
        self,
        row: int,
        split_column: int | None,
        mix_column: int | None,
        expected_split_column: int | None,
        expected_mix_column: int | None,
        expected_preset_name: str,
    ) -> Any:
        """Set or clear a signal-row split and rejoin with complete stale-route guards."""
        return self._invoke_generated_action("set_chain_split", locals())

    def set_split_mute(
        self,
        row: int,
        muted: bool,
        expected_muted: bool,
        expected_preset_name: str,
    ) -> Any:
        """Mute or unmute a splitter/mixer path globally across scenes with exact device readback."""
        return self._invoke_generated_action("set_split_mute", locals())

    def save_preset_as(
        self,
        setlist_key: str,
        position: int,
        name: str,
        expected_preset_name: str,
        expected_position: int,
        confirm_overwrite: bool,
        confirm_persistent_write: bool,
    ) -> Any:
        """Save the current preset to a reviewed device slot with explicit overwrite confirmation."""
        return self._invoke_generated_action("save_preset_as", locals())

    def rename_current_preset(
        self,
        new_name: str,
        expected_preset_name: str,
        expected_position: int,
        confirm_persistent_write: bool,
    ) -> Any:
        """Rename the active stored preset after explicit confirmation."""
        return self._invoke_generated_action("rename_current_preset", locals())

    def copy_preset(
        self,
        source_setlist_key: str,
        source_position: int,
        source_name: str,
        destination_setlist_key: str,
        destination_position: int,
        expected_preset_name: str,
        expected_position: int,
        confirm_overwrite: bool,
        confirm_persistent_write: bool,
    ) -> Any:
        """Copy a device preset to a reviewed destination with explicit overwrite confirmation."""
        return self._invoke_generated_action("copy_preset", locals())

    def get_general_settings(
        self,

    ) -> Any:
        """Read the QC Device Settings and System settings without changing them."""
        return self._invoke_generated_action("get_general_settings", locals())

    def get_io_settings(
        self,

    ) -> Any:
        """Read complete input, output, headphone, USB, MIDI, expression-pedal, connection, and output-pairing settings."""
        return self._invoke_generated_action("get_io_settings", locals())

    def set_input_port(
        self,
        input_port_id: int,
        level_db: float | None,
        impedance: float | None,
        input_type: float | None,
        ground_lift: float | None,
        confirm_persistent_write: bool,
    ) -> Any:
        """Change one or more settings for a QC input. Each supplied field is sent in its own hardware update; input gain is expressed safely in dB."""
        return self._invoke_generated_action("set_input_port", locals())

    def set_output_port(
        self,
        output_port_id: int,
        level: float | None,
        ground_lift: float | None,
        mute: bool | None,
        confirm_persistent_write: bool,
    ) -> Any:
        """Change level, ground lift, or mute for one QC output. Every supplied field is sent in a separate hardware update."""
        return self._invoke_generated_action("set_output_port", locals())

    def set_usb_port(
        self,
        level: float | None,
        headphones_source: float | None,
        dry_wet: float | None,
        confirm_persistent_write: bool,
    ) -> Any:
        """Change USB level, headphone source, or dry/wet routing using normalized device values and separate hardware updates."""
        return self._invoke_generated_action("set_usb_port", locals())

    def set_midi_thru(
        self,
        enabled: bool,
        confirm_persistent_write: bool,
    ) -> Any:
        """Enable or disable the QC MIDI Thru setting after explicit confirmation."""
        return self._invoke_generated_action("set_midi_thru", locals())

    def set_output_pairing(
        self,
        xlr12_linked: bool | None,
        out34_linked: bool | None,
        confirm_persistent_write: bool,
    ) -> Any:
        """Pair or unpair output couples. Null leaves that output couple unchanged."""
        return self._invoke_generated_action("set_output_pairing", locals())

    def get_global_eq(
        self,

    ) -> Any:
        """Read Global EQ bypass state and all 28 normalized parameters."""
        return self._invoke_generated_action("get_global_eq", locals())

    def set_global_eq_bypassed(
        self,
        bypassed: bool,
        confirm_persistent_write: bool,
    ) -> Any:
        """Enable or bypass the global EQ after explicit confirmation."""
        return self._invoke_generated_action("set_global_eq_bypassed", locals())

    def set_global_eq_band(
        self,
        band: int,
        gain: float | None,
        frequency: float | None,
        q: float | None,
        filter_type: int | None,
        enabled: bool | None,
        confirm_persistent_write: bool,
    ) -> Any:
        """Update one Global EQ band with sparse normalized controls after explicit confirmation."""
        return self._invoke_generated_action("set_global_eq_band", locals())

    def set_global_eq_output(
        self,
        level: float | None,
        out12: bool | None,
        out34: bool | None,
        confirm_persistent_write: bool,
    ) -> Any:
        """Update Global EQ output level and output-pair assignments after explicit confirmation."""
        return self._invoke_generated_action("set_global_eq_output", locals())

    def get_mode_cycle(
        self,

    ) -> Any:
        """Read the configured footswitch modes in cycle order."""
        return self._invoke_generated_action("get_mode_cycle", locals())

    def set_mode_cycle(
        self,
        slots: list[int],
        confirm_persistent_write: bool,
    ) -> Any:
        """Replace the ordered footswitch mode cycle after explicit confirmation."""
        return self._invoke_generated_action("set_mode_cycle", locals())

    def get_global_tempo_settings(
        self,

    ) -> Any:
        """Read the device-global tempo block, including PRESET/GLOBAL mode, metronome options, routing, and all thirteen beat cells."""
        return self._invoke_generated_action("get_global_tempo_settings", locals())

    def set_tempo_metronome(
        self,
        led_enabled: bool | None,
        volume_db: float | None,
        running: bool | None,
        pan: float | None,
        time_signature: str | None,
        subdivision: str | None,
        sound: str | None,
        routing: str | None,
        beats: list[str] | None,
        confirm_persistent_write: bool,
    ) -> Any:
        """Change named fields of the loaded preset's tempo/metronome block. Null leaves a field unchanged; time signature is applied before beat cells."""
        return self._invoke_generated_action("set_tempo_metronome", locals())

    def set_tempo_mode(
        self,
        mode: str,
        confirm_persistent_write: bool,
    ) -> Any:
        """Select whether the Quad Cortex uses the loaded preset tempo or its device-global tempo block."""
        return self._invoke_generated_action("set_tempo_mode", locals())

    def get_looper_status(
        self,

    ) -> Any:
        """Read the complete Looper X transport and progress state when a looper is present."""
        return self._invoke_generated_action("get_looper_status", locals())

    def control_looper(
        self,
        command: str,
        value: int | None,
    ) -> Any:
        """Control Looper X through its documented MIDI CC interface."""
        return self._invoke_generated_action("control_looper", locals())

    def list_recents(
        self,

    ) -> Any:
        """List recently used presets with authoritative folder metadata."""
        return self._invoke_generated_action("list_recents", locals())

    def list_favorites(
        self,

    ) -> Any:
        """List favorite presets using request correlation even when the reply omits its favorites flag."""
        return self._invoke_generated_action("list_favorites", locals())

    def set_favorite(
        self,
        name: str,
        folder_key: str,
        folder_name: str,
        is_factory: bool,
        favorite: bool,
        confirm_persistent_write: bool,
    ) -> Any:
        """Add or remove one exact device library entry from Favorites after explicit confirmation."""
        return self._invoke_generated_action("set_favorite", locals())

    def list_pinned_models(
        self,

    ) -> Any:
        """List model IDs and capture keys pinned in the device model browser."""
        return self._invoke_generated_action("list_pinned_models", locals())

    def set_model_pinned(
        self,
        model_id: int,
        pinned: bool,
        confirm_persistent_write: bool,
    ) -> Any:
        """Pin or unpin one model ID after explicit confirmation."""
        return self._invoke_generated_action("set_model_pinned", locals())

    def list_captures(
        self,

    ) -> Any:
        """List loadable Neural Captures with their content keys and names."""
        return self._invoke_generated_action("list_captures", locals())

    def load_capture(
        self,
        row: int,
        column: int,
        key: str,
        name: str,
        model_id: int | None,
        expected_model_id: int | None,
        expected_preset_name: str,
    ) -> Any:
        """Place or retarget a Neural Capture block using a device library key and name, guarded by the current Grid cell and preset."""
        return self._invoke_generated_action("load_capture", locals())

    def list_irs(
        self,
        folder: str | None,
    ) -> Any:
        """List loadable Impulse Responses from the whole library or a selected device folder."""
        return self._invoke_generated_action("list_irs", locals())

    def load_ir(
        self,
        row: int,
        column: int,
        key: str,
        name: str,
        slot: int,
        model_id: int | None,
        expected_model_id: int | None,
        expected_preset_name: str,
    ) -> Any:
        """Place or retarget an IR Loader and set one of its two IR slots by key and name, guarded by the current Grid cell and preset."""
        return self._invoke_generated_action("load_ir", locals())

    def create_setlist(
        self,
        name: str,
        confirm_persistent_write: bool,
    ) -> Any:
        """Create a user setlist after explicit confirmation."""
        return self._invoke_generated_action("create_setlist", locals())

    def delete_setlist(
        self,
        name: str,
        confirm_persistent_write: bool,
    ) -> Any:
        """Delete a named user setlist and its contents after explicit confirmation."""
        return self._invoke_generated_action("delete_setlist", locals())

    def duplicate_setlist(
        self,
        source_setlist_key: str,
        destination_name: str,
        limit: int | None,
        expected_preset_name: str,
        expected_position: int,
        confirm_persistent_write: bool,
    ) -> Any:
        """Create a user setlist and copy its source presets through the shared recall-and-save workflow after explicit confirmation."""
        return self._invoke_generated_action("duplicate_setlist", locals())

    def delete_preset(
        self,
        setlist_key: str,
        name: str,
        confirm_persistent_write: bool,
    ) -> Any:
        """Delete a named preset from a writable user setlist after explicit confirmation."""
        return self._invoke_generated_action("delete_preset", locals())

    def move_preset(
        self,
        setlist_key: str,
        name: str,
        position: int,
        confirm_persistent_write: bool,
    ) -> Any:
        """Move a named preset to another slot in its user setlist after explicit confirmation."""
        return self._invoke_generated_action("move_preset", locals())

    def set_general_integer(
        self,
        setting: str,
        value: int,
        confirm_persistent_write: bool,
    ) -> Any:
        """Change one validated integer Device Setting after explicit confirmation. Hold timing uses its wire index 0 through 5."""
        return self._invoke_generated_action("set_general_integer", locals())

    def set_general_toggle(
        self,
        setting: str,
        enabled: bool,
        confirm_persistent_write: bool,
    ) -> Any:
        """Change one validated on/off Device Setting after explicit confirmation."""
        return self._invoke_generated_action("set_general_toggle", locals())

    def set_scene_bypass_behavior(
        self,
        behavior: str,
        confirm_persistent_write: bool,
    ) -> Any:
        """Change the global scene block-bypass persistence behavior after explicit confirmation."""
        return self._invoke_generated_action("set_scene_bypass_behavior", locals())

    def set_master_volume_assignment(
        self,
        out12: bool,
        out34: bool,
        send12: bool,
        headphones: bool,
        confirm_persistent_write: bool,
    ) -> Any:
        """Replace all four Master Volume output assignments atomically after explicit confirmation."""
        return self._invoke_generated_action("set_master_volume_assignment", locals())

    def set_global_bypass(
        self,
        cab: list[bool],
        ir: list[bool],
        confirm_persistent_write: bool,
    ) -> Any:
        """Replace all Cab and IR global-bypass row flags atomically after explicit confirmation."""
        return self._invoke_generated_action("set_global_bypass", locals())
