// Generated by scripts/generate-qc-relay-profile.mjs. Do not edit by hand.
package com.qccontrol.mobile;

final class GeneratedRelayProfile {
    static final String PROTOCOL_VERSION = "qc-relay.v1";
    static final String DEVICE_PAIR_PATH = "/v1/device/pair";
    static final String DEVICE_CONNECT_PATH = "/v1/device/connect";
    static final int PAIRING_CODE_MINIMUM_LENGTH = 6;
    static final int PAIRING_CODE_MAXIMUM_LENGTH = 128;
    static final int MINIMUM_CREDENTIAL_LENGTH = 24;
    static final int MAX_REQUEST_FRAME_BYTES = 65536;
    static final int MAX_RESULT_FRAME_BYTES = 16777216;
    static final int COMPLETED_REQUEST_CACHE_SIZE = 512;
    static final long READINESS_INTERVAL_MS = 1000L;
    static final long READINESS_GRACE_MS = 1500L;
    static final long PING_INTERVAL_MS = 25000L;
    static final int MAXIMUM_FAILURE_COUNT = 10;
    static final int MAXIMUM_BACKOFF_EXPONENT = 6;
    static final long MAXIMUM_BACKOFF_SECONDS = 60L;
    static final long BACKOFF_JITTER_MS = 1000L;

    private GeneratedRelayProfile() {}
}
