// Generated by scripts/generate-qc-domain.mjs. Do not edit by hand.
package com.qccontrol.mobile;

final class QcDomain {
    static final int GRID_ROWS = 4;
    static final int GRID_COLUMNS = 8;
    static final int SCENE_COUNT = 8;
    static final int MINIMUM_TEMPO_BPM = 40;
    static final int MAXIMUM_TEMPO_BPM = 240;
    static final int STORED_PRESET_NAME_CHARACTERS = 20;
    static final int IPC_MAX_FRAME_BYTES = 16777216;
    static final int STATE_EVENT_DEFAULT_LIMIT = 256;
    static final int STATE_EVENT_MAXIMUM_LIMIT = 4096;
    private QcDomain() {}
}
