// Generated by scripts/generate-qc-usb-profile.mjs. Do not edit by hand.
package com.qccontrol.mobile;

final class QcUsbProfile {
    static final int VENDOR_ID = 5418;
    static final int PRODUCT_ID = 34826;
    static final String CORTEX_CONTROL_VERSION = "4.0.1";
    static final int MAX_FRAME_BYTES = 1048576;
    static final int MAX_INFLATED_BYTES = 16777216;
    static final long KEEPALIVE_INTERVAL_MS = 5000L;
    static final long LIVENESS_REPLY_TIMEOUT_MS = 3000L;
    static final long RECONNECT_INTERVAL_MS = 750L;
    static final long PERFORMANCE_MIDI_GAP_MS = 8L;
    static final long HANDSHAKE_TIMEOUT_MS = 30000L;
    static final long HANDSHAKE_ATTEMPT_TIMEOUT_MS = 5000L;
    static final long INITIAL_SYNC_TIMEOUT_MS = 2000L;
    static final long READY_WAIT_TIMEOUT_MS = 35000L;
    static final long PRESET_SYNC_TIMEOUT_MS = 15000L;
    static final long COMMAND_CONFIRMATION_TIMEOUT_MS = 3000L;
    static final long BACKUP_TOTAL_TIMEOUT_MS = 180000L;
    static final long BACKUP_FIRST_CHUNK_TIMEOUT_MS = 60000L;
    static final long BACKUP_STREAM_STALL_TIMEOUT_MS = 15000L;
    static final int BACKUP_MAXIMUM_ATTEMPTS = 2;
    static final int BACKUP_MAXIMUM_DOCUMENT_BYTES = 33554432;
    static final int MIDI_CONTROL_CHANGE_STATUS = 176;
    static final int MIDI_USB_EVENT_PACKET_HEADER = 11;
    static final int FOOTSWITCH_BASE_CONTROLLER = 35;
    static final int TAP_TEMPO_CONTROLLER = 44;
    static final int TUNER_CONTROLLER = 45;
    static final int GIG_VIEW_CONTROLLER = 46;
    static final int MODE_SLOT_CONTROLLER = 47;
    static final int MIDI_PRESSED_VALUE = 127;
    static final int MIDI_FEATURE_OFF_VALUE = 0;
    static final int MIDI_FEATURE_ON_VALUE = 127;
    static final int MESSAGE_TYPE_VERSION = 10;
    static final int MESSAGE_TYPE_PRESET = 15;
    static final int MESSAGE_TYPE_GLOBAL_TEMPO = 33;
    static final int MESSAGE_TYPE_BACKUP = 40;
    static final int MESSAGE_TYPE_MODEL_REPO = 51;
    static final int MESSAGE_TYPE_RESET_COMMS_BUFFERS = 52;
    static final int MESSAGE_TYPE_SYSTEM_TIME_SYNC = 43;
    static final int[] LIVE_SUBSCRIPTIONS = {3, 9, 24, 38, 20, 42, 35, 58, 50, 54, 19, 15, 57, 60, 17, 33, 34, 21, 2, 13, 14};

    private QcUsbProfile() {}
}
