# Generated by scripts/generate-qc-domain.mjs. Do not edit by hand.
GRID_ROWS = 4
GRID_COLUMNS = 8
SCENE_COUNT = 8
MINIMUM_TEMPO_BPM = 40
MAXIMUM_TEMPO_BPM = 240
STORED_PRESET_NAME_CHARACTERS = 20
IPC_MAX_FRAME_BYTES = 16777216
STATE_EVENT_DEFAULT_LIMIT = 256
STATE_EVENT_MAXIMUM_LIMIT = 4096
SCENE_COLORS = ["#ff2727","#0a74e0","#ffd236","#ff02c2","#45f862","#ff7000","#6954ff","#00ffdd"]
CATEGORY_COLORS = {"plugin":"#ff7000","amp":"#ff2727","capture":"#959595","cab":"#6954ff","overdrive":"#ff7000","delay":"#00ffdd","reverb":"#00ffdd","compressor":"#45f862","pitch":"#ffd236","modulation":"#3500f1","morph":"#87daff","synth":"#e44a5d","filter":"#87daff","equalizer":"#0a74e0","irLoader":"#6954ff","wah":"#959595","fxLoop":"#959595","looper":"#ff2727","utility":"#959595"}
HARDWARE_COLORS = {"whiteLed":"#f4f4f4","idleLed":"#626367","metalHighlight":"#c5c6c8","metalMid":"#8f9194","metalShadow":"#222327"}
INPUT_ROUTE_LABELS = {1: "In 1", 2: "In 2", 4: "Return 1", 5: "Return 2", 8: "USB 5", 9: "USB 6", 10: "USB 7", 11: "USB 8", 3: "In 1/2", 6: "Return 1/2", 12: "USB 5/6", 13: "USB 7/8", 7: "Prev. Row", 0: "Internal"}
OUTPUT_ROUTE_LABELS = {19: "Multi Out", 1: "Out 1/2", 2: "Out 3/4", 3: "Send 1/2", 22: "USB 3/4", 14: "USB 5/6", 15: "USB 7/8", 4: "Out 1", 5: "Out 2", 6: "Out 3", 7: "Out 4", 8: "Send 1", 9: "Send 2", 20: "USB 3", 21: "USB 4", 10: "USB 5", 11: "USB 6", 12: "USB 7", 13: "USB 8", 16: "Row 3", 17: "Row 4", 18: "Row 3/4", 0: "Internal"}
