// Generated by scripts/generate-qc-domain.mjs. Do not edit by hand.
pub const GRID_ROWS: u32 = 4;
pub const GRID_COLUMNS: u32 = 8;
pub const SCENE_COUNT: u32 = 8;
pub const MINIMUM_TEMPO_BPM: u32 = 40;
pub const MAXIMUM_TEMPO_BPM: u32 = 240;
pub const STORED_PRESET_NAME_CHARACTERS: usize = 20;
pub const IPC_MAX_FRAME_BYTES: usize = 16777216;
pub const STATE_EVENT_DEFAULT_LIMIT: usize = 256;
pub const STATE_EVENT_MAXIMUM_LIMIT: usize = 4096;
pub const SCENE_COLORS: &[&str] = &[
    "#ff2727", "#0a74e0", "#ffd236", "#ff02c2", "#45f862", "#ff7000", "#6954ff", "#00ffdd",
];
pub mod visual_colors {
    pub const PLUGIN: &str = "#ff7000";
    pub const AMP: &str = "#ff2727";
    pub const CAPTURE: &str = "#959595";
    pub const CAB: &str = "#6954ff";
    pub const OVERDRIVE: &str = "#ff7000";
    pub const DELAY: &str = "#00ffdd";
    pub const REVERB: &str = "#00ffdd";
    pub const COMPRESSOR: &str = "#45f862";
    pub const PITCH: &str = "#ffd236";
    pub const MODULATION: &str = "#3500f1";
    pub const MORPH: &str = "#87daff";
    pub const SYNTH: &str = "#e44a5d";
    pub const FILTER: &str = "#87daff";
    pub const EQUALIZER: &str = "#0a74e0";
    pub const IR_LOADER: &str = "#6954ff";
    pub const WAH: &str = "#959595";
    pub const FX_LOOP: &str = "#959595";
    pub const LOOPER: &str = "#ff2727";
    pub const UTILITY: &str = "#959595";
    pub const WHITE_LED: &str = "#f4f4f4";
    pub const IDLE_LED: &str = "#626367";
    pub const METAL_HIGHLIGHT: &str = "#c5c6c8";
    pub const METAL_MID: &str = "#8f9194";
    pub const METAL_SHADOW: &str = "#222327";
}
pub const INPUT_ROUTES: &[(u32, &str)] = &[
    (1, "In 1"),
    (2, "In 2"),
    (4, "Return 1"),
    (5, "Return 2"),
    (8, "USB 5"),
    (9, "USB 6"),
    (10, "USB 7"),
    (11, "USB 8"),
    (3, "In 1/2"),
    (6, "Return 1/2"),
    (12, "USB 5/6"),
    (13, "USB 7/8"),
    (7, "Prev. Row"),
    (0, "Internal"),
];
pub const OUTPUT_ROUTES: &[(u32, &str)] = &[
    (19, "Multi Out"),
    (1, "Out 1/2"),
    (2, "Out 3/4"),
    (3, "Send 1/2"),
    (22, "USB 3/4"),
    (14, "USB 5/6"),
    (15, "USB 7/8"),
    (4, "Out 1"),
    (5, "Out 2"),
    (6, "Out 3"),
    (7, "Out 4"),
    (8, "Send 1"),
    (9, "Send 2"),
    (20, "USB 3"),
    (21, "USB 4"),
    (10, "USB 5"),
    (11, "USB 6"),
    (12, "USB 7"),
    (13, "USB 8"),
    (16, "Row 3"),
    (17, "Row 4"),
    (18, "Row 3/4"),
    (0, "Internal"),
];
