// Generated by scripts/generate-qc-payloads.mjs. Do not edit by hand.
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TunerSettings {
    pub input_port_id: i32,
    pub reference_offset_hz: f32,
    pub reference_hz: f32,
    pub muted: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GlobalBypassRows {
    pub row1: bool,
    pub row2: bool,
    pub row3: bool,
    pub row4: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MasterVolumeAssignment {
    pub out12: bool,
    pub out34: bool,
    pub send12: bool,
    pub headphones: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GeneralSettings {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub screen_brightness: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub led_brightness: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dimmed_led_brightness: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lock_screen_and_volume_knob: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub global_bypass_cab: Option<GlobalBypassRows>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub global_bypass_ir: Option<GlobalBypassRows>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scene_bypass_behavior: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub midi_over_usb: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub midi_channel: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ignore_duplicate_pc: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub available_disk_space: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_disk_space: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub internal_midi_clock_enabled: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub master_volume_assignment: Option<MasterVolumeAssignment>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stomp_mode_auto_assign: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub swap_tempo_tuner_access: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub midi_clock_out: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disable_internet_connection_check: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dynamic_delay_compensation: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preset_dimmed: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scene_dimmed: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stomp_dimmed: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub midi_clock_in: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gig_view_stomp_access: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hold_timing_index: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hold_timing_ms: Option<i32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InputPortSettings {
    pub input_port_id: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub level: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub level_db: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub impedance: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_type: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ground_lift: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plugged: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OutputPortSettings {
    pub output_port_id: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub level: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ground_lift: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub muted: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plugged: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HeadphonesFeed {
    pub output_port_id: u32,
    pub level: f32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HeadphonesSettings {
    pub feeds: Vec<HeadphonesFeed>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub level: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plugged: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UsbPortSettings {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub level: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub headphones_source: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plugged: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dry_wet: Option<f32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExpressionPortSettings {
    pub expression_port_id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plugged: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub level: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub calibrating: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MidiPortSettings {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thru: Option<f32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IoSettings {
    pub inputs: Vec<InputPortSettings>,
    pub outputs: Vec<OutputPortSettings>,
    pub expression_ports: Vec<ExpressionPortSettings>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub headphones: Option<HeadphonesSettings>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usb: Option<UsbPortSettings>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub midi: Option<MidiPortSettings>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub xlr12_linked: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub out34_linked: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GlobalEqParameter {
    pub parameter_index: i32,
    pub value: f32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GlobalEqSettings {
    pub parameters: Vec<GlobalEqParameter>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bypassed: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModeCycle {
    pub slots: Vec<u32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TempoSettings {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bpm: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub global_bpm: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub led_enabled: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub volume_db: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub running: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pan: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_signature: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subdivision: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sound: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub routing: Option<String>,
    pub beats: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TempoModeSettings {
    pub mode: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LooperStatus {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub progress: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub undo_progress: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duplicate_cycle: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub num_duplicate_cycles: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub one_shot_stopped: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub redo_available: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub loop_length: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub free_samples: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub in_reverse: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub one_shot: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub half_speed: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fixed_duplicate_cycles: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub armed: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub waiting_for_cycle: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub undo_count: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_write_displacement: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_write_displacement: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub events_waiting_for_quantize: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub current_clock: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transition: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub one_shot_play: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sync_start_waiting: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantize_enabled: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_type: Option<i32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BypassExpression {
    pub pedal: u32,
    pub minimum: f32,
    pub maximum: f32,
    pub mode: u32,
    pub invert: bool,
    pub delay_ms: u32,
    pub latch_emulation: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GridBlock {
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_id: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category_id: Option<u32>,
    pub name: String,
    pub kind: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plugin: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plugin_id: Option<String>,
    pub row: u32,
    pub column: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bypassed: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bypass_expression: Option<BypassExpression>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub glyph: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub footswitch: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub footswitch_order: Option<u32>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FootswitchState {
    pub index: u32,
    pub active: bool,
    pub assigned: bool,
    pub color: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub momentary: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MidiOutMessage {
    pub r#type: u32,
    pub channel: u32,
    pub param1: u32,
    pub param2: u32,
    pub param3: u32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MidiOutSource {
    pub source: u32,
    pub messages: Vec<MidiOutMessage>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GridRoute {
    pub row: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_id: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_id: Option<u32>,
    pub input: String,
    pub output: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub split_column: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mix_column: Option<i32>,
    pub split_muted: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IoPortState {
    pub kind: String,
    pub id: i32,
    pub label: String,
    pub plugged: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModeSlot {
    pub slot: u32,
    pub label: String,
    pub mode: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BypassUpdate {
    pub row: u32,
    pub column: u32,
    pub bypassed: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QcStateUpdate {
    pub kind: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active_scene: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dirty: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub master_volume: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub index: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub setlist_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_factory: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preset_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tempo: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tempo_led_enabled: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scenes: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scene_colors: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub footswitch_states: Option<Vec<FootswitchState>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub midi_out: Option<Vec<MidiOutSource>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preset_load_midi_out: Option<Vec<MidiOutMessage>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub blocks: Option<Vec<GridBlock>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub routes: Option<Vec<GridRoute>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub io_ports: Option<Vec<IoPortState>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode_slots: Option<Vec<ModeSlot>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub footswitch_modes: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub row: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub column: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bypassed: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bypass_updates: Option<Vec<BypassUpdate>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameter_index: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub normalized_value: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub catalog_refresh: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub observed_at: Option<u64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ScalePoint {
    pub normalized: f64,
    pub real: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BlockParameter {
    pub index: u32,
    pub display_position: u32,
    pub name: String,
    pub normalized_value: Option<f64>,
    pub display_value: String,
    pub units: String,
    pub r#type: String,
    pub minimum: f64,
    pub maximum: f64,
    pub value_scale: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scale_exponent: Option<f64>,
    pub scale_points: Vec<ScalePoint>,
    pub scale_known: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_precision: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub minimum_label: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub midpoint_label: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub maximum_label: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub steps: Option<u32>,
    pub scene_mode: bool,
    pub options: Vec<String>,
    pub writable: bool,
    pub enabled: bool,
    pub expression_assignable: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub linked_scene_mode: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expression: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expression_minimum: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expression_maximum: Option<f32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub led_value: Option<f32>,
    pub wire_value_kind: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BlockDetails {
    pub row: u32,
    pub column: u32,
    pub model_id: u32,
    pub name: String,
    pub category: String,
    pub scene: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bypass_expression: Option<BypassExpression>,
    pub parameters: Vec<BlockParameter>,
}
