# Generated by scripts/generate-qc-payloads.mjs. Do not edit by hand.
from __future__ import annotations
from typing import Any, Literal, NotRequired, TypedDict


class TunerSettings(TypedDict):
    inputPortId: int
    referenceOffsetHz: float
    referenceHz: float
    muted: bool

class GlobalBypassRows(TypedDict):
    row1: bool
    row2: bool
    row3: bool
    row4: bool

class MasterVolumeAssignment(TypedDict):
    out12: bool
    out34: bool
    send12: bool
    headphones: bool

class GeneralSettings(TypedDict):
    screenBrightness: NotRequired[int]
    ledBrightness: NotRequired[int]
    dimmedLedBrightness: NotRequired[int]
    lockScreenAndVolumeKnob: NotRequired[bool]
    globalBypassCab: NotRequired[GlobalBypassRows]
    globalBypassIr: NotRequired[GlobalBypassRows]
    sceneBypassBehavior: NotRequired[Literal["alwaysOverwrite", "nonstompOverwrite", "neverOverwrite"]]
    midiOverUsb: NotRequired[bool]
    midiChannel: NotRequired[int]
    ignoreDuplicatePc: NotRequired[bool]
    availableDiskSpace: NotRequired[float]
    totalDiskSpace: NotRequired[float]
    internalMidiClockEnabled: NotRequired[bool]
    masterVolumeAssignment: NotRequired[MasterVolumeAssignment]
    stompModeAutoAssign: NotRequired[bool]
    swapTempoTunerAccess: NotRequired[bool]
    midiClockOut: NotRequired[Literal["off", "midiDinOnly", "usbMidiOnly", "bothUsbAndDinMidi"]]
    disableInternetConnectionCheck: NotRequired[bool]
    dynamicDelayCompensation: NotRequired[bool]
    presetDimmed: NotRequired[bool]
    sceneDimmed: NotRequired[bool]
    stompDimmed: NotRequired[bool]
    midiClockIn: NotRequired[bool]
    gigViewStompAccess: NotRequired[bool]
    holdTimingIndex: NotRequired[int]
    holdTimingMs: NotRequired[int]

class InputPortSettings(TypedDict):
    inputPortId: int
    level: NotRequired[float]
    levelDb: NotRequired[float]
    impedance: NotRequired[float]
    inputType: NotRequired[float]
    groundLift: NotRequired[float]
    plugged: NotRequired[bool]

class OutputPortSettings(TypedDict):
    outputPortId: int
    level: NotRequired[float]
    groundLift: NotRequired[float]
    muted: NotRequired[bool]
    plugged: NotRequired[bool]

class HeadphonesFeed(TypedDict):
    outputPortId: int
    level: float

class HeadphonesSettings(TypedDict):
    feeds: list[HeadphonesFeed]
    level: NotRequired[float]
    plugged: NotRequired[bool]

class UsbPortSettings(TypedDict):
    level: NotRequired[float]
    headphonesSource: NotRequired[float]
    plugged: NotRequired[bool]
    dryWet: NotRequired[float]

class ExpressionPortSettings(TypedDict):
    expressionPortId: int
    plugged: NotRequired[bool]
    level: NotRequired[float]
    calibrating: NotRequired[bool]

class MidiPortSettings(TypedDict):
    thru: NotRequired[float]

class IoSettings(TypedDict):
    inputs: list[InputPortSettings]
    outputs: list[OutputPortSettings]
    expressionPorts: list[ExpressionPortSettings]
    headphones: NotRequired[HeadphonesSettings]
    usb: NotRequired[UsbPortSettings]
    midi: NotRequired[MidiPortSettings]
    xlr12Linked: NotRequired[bool]
    out34Linked: NotRequired[bool]

class GlobalEqParameter(TypedDict):
    parameterIndex: int
    value: float

class GlobalEqSettings(TypedDict):
    parameters: list[GlobalEqParameter]
    bypassed: NotRequired[bool]
    hasUserDefaults: NotRequired[bool]

class ModeCycle(TypedDict):
    slots: list[int]

class TempoSettings(TypedDict):
    mode: NotRequired[Literal["PRESET", "GLOBAL"]]
    bpm: NotRequired[int]
    globalBpm: NotRequired[int]
    ledEnabled: NotRequired[bool]
    volumeDb: NotRequired[float]
    running: NotRequired[bool]
    pan: NotRequired[float]
    timeSignature: NotRequired[Literal["2/4", "3/4", "4/4", "5/4", "6/4", "7/4", "8/4", "9/4", "10/4", "11/4", "12/4", "13/4", "3/8", "6/8", "9/8", "12/8", "5/8 (3+2)", "5/8 (2+3)", "7/8 (3+2+2)", "7/8 (2+3+2)", "7/8 (2+2+3)"]]
    subdivision: NotRequired[Literal["1/4", "1/8", "1/8T", "1/16"]]
    sound: NotRequired[Literal["BLIP", "BLOCK", "COWBELL", "DIGITAL", "DRUM KIT", "SOFT KIT"]]
    routing: NotRequired[Literal["MULTI", "HP", "OUT 1/2", "OUT 3/4", "SEND 1/2"]]
    beats: list[Literal["OFF", "MUTE", "DOWN", "ON"]]

class TempoModeSettings(TypedDict):
    mode: Literal["PRESET", "GLOBAL"]

class LooperStatus(TypedDict):
    state: NotRequired[int]
    progress: NotRequired[float]
    undoProgress: NotRequired[float]
    duplicateCycle: NotRequired[int]
    numDuplicateCycles: NotRequired[int]
    oneShotStopped: NotRequired[int]
    redoAvailable: NotRequired[int]
    loopLength: NotRequired[int]
    freeSamples: NotRequired[int]
    inReverse: NotRequired[int]
    oneShot: NotRequired[int]
    halfSpeed: NotRequired[int]
    fixedDuplicateCycles: NotRequired[int]
    armed: NotRequired[int]
    waitingForCycle: NotRequired[int]
    undoCount: NotRequired[int]
    maxWriteDisplacement: NotRequired[float]
    minWriteDisplacement: NotRequired[float]
    eventsWaitingForQuantize: NotRequired[int]
    currentClock: NotRequired[int]
    transition: NotRequired[int]
    action: NotRequired[int]
    oneShotPlay: NotRequired[bool]
    syncStartWaiting: NotRequired[bool]
    quantizeEnabled: NotRequired[bool]
    updateType: NotRequired[int]

class BypassExpression(TypedDict):
    pedal: int
    minimum: float
    maximum: float
    mode: int
    invert: bool
    delayMs: int
    latchEmulation: bool

class GridBlock(TypedDict):
    id: str
    modelId: NotRequired[int]
    categoryId: NotRequired[int]
    name: str
    kind: Literal["input", "utility", "capture", "amp", "cab", "mod", "delay", "reverb", "output"]
    category: NotRequired[str]
    plugin: NotRequired[bool]
    pluginId: NotRequired[str]
    row: int
    column: int
    bypassed: NotRequired[bool]
    bypassExpression: NotRequired[BypassExpression]
    color: NotRequired[str]
    glyph: NotRequired[str]
    footswitch: NotRequired[int]
    footswitchOrder: NotRequired[int]

class FootswitchState(TypedDict):
    index: int
    active: bool
    assigned: bool
    color: str
    momentary: NotRequired[bool]
    label: NotRequired[str]

class MidiOutMessage(TypedDict):
    type: int
    channel: int
    param1: int
    param2: int
    param3: int

class MidiOutSource(TypedDict):
    source: int
    messages: list[MidiOutMessage]

class GridRoute(TypedDict):
    row: int
    inputId: NotRequired[int]
    outputId: NotRequired[int]
    input: str
    output: str
    splitColumn: NotRequired[int]
    mixColumn: NotRequired[int]
    splitMuted: bool

class IoPortState(TypedDict):
    kind: Literal["input", "output", "headphones", "usb", "expression"]
    id: int
    label: str
    plugged: bool

class ModeSlot(TypedDict):
    slot: Literal[0, 1, 2]
    label: str
    mode: Literal["PRESET", "SCENE", "STOMP", "HYBRID"]

class BypassUpdate(TypedDict):
    row: int
    column: int
    bypassed: bool

class QcStateUpdate(TypedDict):
    kind: Literal["scene", "dirty", "master", "sceneLabel", "sceneColor", "position", "preset", "bypass", "bypassBatch", "mode", "tempo", "parameter", "ioPorts"]
    activeScene: NotRequired[int]
    dirty: NotRequired[bool]
    masterVolume: NotRequired[float]
    index: NotRequired[int]
    label: NotRequired[str]
    color: NotRequired[str]
    setlistKey: NotRequired[str]
    position: NotRequired[int]
    isFactory: NotRequired[bool]
    presetName: NotRequired[str]
    tempo: NotRequired[int]
    tempoLedEnabled: NotRequired[bool]
    scenes: NotRequired[list[str]]
    sceneColors: NotRequired[list[str]]
    footswitchStates: NotRequired[list[FootswitchState]]
    midiOut: NotRequired[list[MidiOutSource]]
    presetLoadMidiOut: NotRequired[list[MidiOutMessage]]
    blocks: NotRequired[list[GridBlock]]
    routes: NotRequired[list[GridRoute]]
    ioPorts: NotRequired[list[IoPortState]]
    mode: NotRequired[Literal["PRESET", "SCENE", "STOMP", "HYBRID"]]
    modeSlots: NotRequired[list[ModeSlot]]
    footswitchModes: NotRequired[list[Literal["PRESET", "SCENE", "STOMP"]]]
    row: NotRequired[int]
    column: NotRequired[int]
    bypassed: NotRequired[bool]
    bypassUpdates: NotRequired[list[BypassUpdate]]
    parameterIndex: NotRequired[int]
    normalizedValue: NotRequired[float]
    catalogRefresh: NotRequired[bool]
    observedAt: NotRequired[int]

class ScalePoint(TypedDict):
    normalized: float
    real: float

class BlockParameter(TypedDict):
    index: int
    displayPosition: int
    name: str
    normalizedValue: float | None
    displayValue: str
    units: str
    type: str
    minimum: float
    maximum: float
    valueScale: str
    scaleExponent: NotRequired[float | None]
    scalePoints: list[ScalePoint]
    scaleKnown: bool
    displayPrecision: NotRequired[int | None]
    minimumLabel: NotRequired[str | None]
    midpointLabel: NotRequired[str | None]
    maximumLabel: NotRequired[str | None]
    steps: NotRequired[int | None]
    sceneMode: bool
    options: list[str]
    writable: bool
    enabled: bool
    expressionAssignable: bool
    linkedSceneMode: NotRequired[int | None]
    expression: NotRequired[int | None]
    expressionMinimum: NotRequired[float | None]
    expressionMaximum: NotRequired[float | None]
    ledValue: NotRequired[float | None]
    wireValueKind: str

class BlockDetails(TypedDict):
    row: int
    column: int
    modelId: int
    name: str
    category: str
    scene: int
    bypassExpression: NotRequired[BypassExpression]
    parameters: list[BlockParameter]

class PresetSnapshot(TypedDict):
    deviceName: str
    presetName: str
    presetLocation: str
    presetPosition: int
    setlistKey: str
    setlistName: str
    mode: Literal["PRESET", "SCENE", "STOMP", "HYBRID"]
    modeSlots: NotRequired[list[ModeSlot]]
    footswitchModes: NotRequired[list[Literal["PRESET", "SCENE", "STOMP"]]]
    activeScene: int
    scenes: list[str]
    sceneColors: NotRequired[list[str]]
    footswitchStates: NotRequired[list[FootswitchState]]
    midiOut: NotRequired[list[MidiOutSource]]
    presetLoadMidiOut: NotRequired[list[MidiOutMessage]]
    blocks: list[GridBlock]
    routes: list[GridRoute]
    ioPorts: NotRequired[list[IoPortState]]
    tempo: int
    tempoLedEnabled: NotRequired[bool]
    tempoPulseEpochMs: NotRequired[int]
    masterVolume: float
    dirty: bool

class DeviceActionResult(TypedDict):
    detail: str
    accepted: NotRequired[bool]
    verified: NotRequired[bool]
    verification: NotRequired[Literal["authoritative_readback", "accepted_unverified"]]
    snapshot: NotRequired[PresetSnapshot]
