// Generated by scripts/generate-qc-relay-profile.mjs. Do not edit by hand.
pub const PROTOCOL_VERSION: &str = "qc-relay.v1";
pub const DEVICE_PAIR_PATH: &str = "/v1/device/pair";
pub const DEVICE_CONNECT_PATH: &str = "/v1/device/connect";
pub const PAIRING_CODE_MINIMUM_LENGTH: usize = 6;
pub const PAIRING_CODE_MAXIMUM_LENGTH: usize = 128;
pub const MINIMUM_CREDENTIAL_LENGTH: usize = 24;
pub const MAX_REQUEST_FRAME_BYTES: usize = 65536;
pub const MAX_RESULT_FRAME_BYTES: usize = 16777216;
pub const COMPLETED_REQUEST_CACHE_SIZE: usize = 512;
pub const READINESS_INTERVAL_MS: u64 = 1000;
pub const READINESS_GRACE_MS: u64 = 1500;
pub const MAXIMUM_FAILURE_COUNT: u32 = 10;
pub const MAXIMUM_BACKOFF_EXPONENT: u32 = 6;
pub const MAXIMUM_BACKOFF_SECONDS: u64 = 60;
pub const BACKOFF_JITTER_MS: u64 = 1000;
