// Generated by scripts/generate-gateway-bindings.mjs. Do not edit by hand.
pub const API_VERSION: u64 = 19;
pub const CAPABILITIES: &[&str] = &[
    "modelRepoParameterMetadata",
    "nativeBroker",
    "nativeStateEvents",
    "nativeDeviceIdentity",
    "nativeRemoteScreen",
    "nativeGraphicsTree",
    "nativeScreenGestures",
    "nativeSceneManagement",
    "nativeParameterAssignments",
    "nativeStompMetadata",
    "nativePresetMidiOut",
    "nativeExpressionBypass",
    "nativeTunerSettings",
    "nativeTunerWrites",
    "nativeTunerMeter",
    "nativeLaneControls",
    "nativeGeneralSettings",
    "nativeIoSettings",
    "nativeGlobalEq",
    "nativeModeCycle",
    "nativeLooper",
    "nativeLibraryManagement",
    "nativeSplitMute",
    "nativeTempoMetronome",
    "nativeGlobalTempoWrite",
];
pub const METHODS: &[&str] = &[
    "system.status",
    "device.reconnect",
    "device.resetSession",
    "device.disconnect",
    "device.snapshot",
    "device.stateEvents",
    "device.tempoClock",
    "device.listModels",
    "device.identity",
    "device.setDeviceName",
    "device.undo",
    "device.redo",
    "device.inhibitedModules",
    "device.tunerSettings",
    "device.setTunerInput",
    "device.setTunerMute",
    "device.restoreTunerAudio",
    "device.setTunerReference",
    "device.setTunerMeter",
    "device.generalSettings",
    "device.ioSettings",
    "device.setInputPort",
    "device.setOutputPort",
    "device.setUsbPort",
    "device.setMidiThru",
    "device.setOutputPairing",
    "device.globalEq",
    "device.setGlobalEqBypassed",
    "device.setGlobalEqBand",
    "device.setGlobalEqOutput",
    "device.modeCycle",
    "device.setModeCycle",
    "device.globalTempoSettings",
    "device.setTempoMetronome",
    "device.setTempoMode",
    "device.setGlobalTempo",
    "device.looperStatus",
    "device.controlLooper",
    "device.recents",
    "device.favorites",
    "device.setFavorite",
    "device.pinnedModels",
    "device.setModelPinned",
    "device.captures",
    "device.loadCapture",
    "device.irs",
    "device.loadIr",
    "device.createSetlist",
    "device.deleteSetlist",
    "device.duplicateSetlist",
    "device.deletePreset",
    "device.movePreset",
    "device.setGeneralInteger",
    "device.setGeneralToggle",
    "device.setSceneBypassBehavior",
    "device.setMasterVolumeAssignment",
    "device.setGlobalBypass",
    "device.presetScreenshot",
    "device.captureScreen",
    "device.graphicsTree",
    "device.tapScreen",
    "device.swipeScreen",
    "device.selectScene",
    "device.copyScene",
    "device.setSceneLabel",
    "device.setSceneColor",
    "device.toggleBypass",
    "device.moveBlock",
    "device.addBlock",
    "device.removeBlock",
    "device.setBlockFootswitch",
    "device.setStompMomentary",
    "device.setStompLabel",
    "device.setMidiOut",
    "device.setPresetLoadMidiOut",
    "device.setExpressionBypass",
    "device.setChainInput",
    "device.setChainOutput",
    "device.setChainSplit",
    "device.setSplitMute",
    "device.listPresets",
    "device.listPresetFolders",
    "device.navigateBank",
    "device.recallPreset",
    "device.reloadPreset",
    "device.blockDetails",
    "device.laneControlDetails",
    "device.previewParameter",
    "device.previewLaneControlParameter",
    "device.setParameter",
    "device.setLaneControlParameter",
    "device.setLaneControlSceneMode",
    "device.setParameterSceneMode",
    "device.setParameterExpression",
    "device.setTempo",
    "device.setMasterVolume",
    "device.masterVolume",
    "device.pressFootswitch",
    "device.tapTempo",
    "device.selectModeSlot",
    "device.listPresetSlots",
    "device.savePresetAs",
    "device.copyPreset",
    "device.renameCurrentPreset",
    "device.createBackup",
    "device.showTuner",
    "device.showGigView",
];
pub const PERFORMANCE_MIDI_METHODS: &[&str] = &[
    "device.controlLooper",
    "device.pressFootswitch",
    "device.tapTempo",
    "device.selectModeSlot",
    "device.showTuner",
    "device.showGigView",
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GatewayResultKind {
    Object,
    PresetSnapshot,
    DeviceActionResult,
}

pub fn result_kind(method: &str) -> Option<GatewayResultKind> {
    match method {
        "system.status" => Some(GatewayResultKind::Object),
        "device.reconnect" => Some(GatewayResultKind::Object),
        "device.resetSession" => Some(GatewayResultKind::Object),
        "device.disconnect" => Some(GatewayResultKind::Object),
        "device.snapshot" => Some(GatewayResultKind::PresetSnapshot),
        "device.stateEvents" => Some(GatewayResultKind::Object),
        "device.tempoClock" => Some(GatewayResultKind::Object),
        "device.listModels" => Some(GatewayResultKind::Object),
        "device.identity" => Some(GatewayResultKind::Object),
        "device.setDeviceName" => Some(GatewayResultKind::DeviceActionResult),
        "device.undo" => Some(GatewayResultKind::DeviceActionResult),
        "device.redo" => Some(GatewayResultKind::DeviceActionResult),
        "device.inhibitedModules" => Some(GatewayResultKind::Object),
        "device.tunerSettings" => Some(GatewayResultKind::Object),
        "device.setTunerInput" => Some(GatewayResultKind::DeviceActionResult),
        "device.setTunerMute" => Some(GatewayResultKind::DeviceActionResult),
        "device.restoreTunerAudio" => Some(GatewayResultKind::DeviceActionResult),
        "device.setTunerReference" => Some(GatewayResultKind::DeviceActionResult),
        "device.setTunerMeter" => Some(GatewayResultKind::DeviceActionResult),
        "device.generalSettings" => Some(GatewayResultKind::Object),
        "device.ioSettings" => Some(GatewayResultKind::Object),
        "device.setInputPort" => Some(GatewayResultKind::DeviceActionResult),
        "device.setOutputPort" => Some(GatewayResultKind::DeviceActionResult),
        "device.setUsbPort" => Some(GatewayResultKind::DeviceActionResult),
        "device.setMidiThru" => Some(GatewayResultKind::DeviceActionResult),
        "device.setOutputPairing" => Some(GatewayResultKind::DeviceActionResult),
        "device.globalEq" => Some(GatewayResultKind::Object),
        "device.setGlobalEqBypassed" => Some(GatewayResultKind::DeviceActionResult),
        "device.setGlobalEqBand" => Some(GatewayResultKind::DeviceActionResult),
        "device.setGlobalEqOutput" => Some(GatewayResultKind::DeviceActionResult),
        "device.modeCycle" => Some(GatewayResultKind::Object),
        "device.setModeCycle" => Some(GatewayResultKind::DeviceActionResult),
        "device.globalTempoSettings" => Some(GatewayResultKind::Object),
        "device.setTempoMetronome" => Some(GatewayResultKind::DeviceActionResult),
        "device.setTempoMode" => Some(GatewayResultKind::DeviceActionResult),
        "device.setGlobalTempo" => Some(GatewayResultKind::DeviceActionResult),
        "device.looperStatus" => Some(GatewayResultKind::Object),
        "device.controlLooper" => Some(GatewayResultKind::DeviceActionResult),
        "device.recents" => Some(GatewayResultKind::Object),
        "device.favorites" => Some(GatewayResultKind::Object),
        "device.setFavorite" => Some(GatewayResultKind::DeviceActionResult),
        "device.pinnedModels" => Some(GatewayResultKind::Object),
        "device.setModelPinned" => Some(GatewayResultKind::DeviceActionResult),
        "device.captures" => Some(GatewayResultKind::Object),
        "device.loadCapture" => Some(GatewayResultKind::DeviceActionResult),
        "device.irs" => Some(GatewayResultKind::Object),
        "device.loadIr" => Some(GatewayResultKind::DeviceActionResult),
        "device.createSetlist" => Some(GatewayResultKind::DeviceActionResult),
        "device.deleteSetlist" => Some(GatewayResultKind::DeviceActionResult),
        "device.duplicateSetlist" => Some(GatewayResultKind::DeviceActionResult),
        "device.deletePreset" => Some(GatewayResultKind::DeviceActionResult),
        "device.movePreset" => Some(GatewayResultKind::DeviceActionResult),
        "device.setGeneralInteger" => Some(GatewayResultKind::DeviceActionResult),
        "device.setGeneralToggle" => Some(GatewayResultKind::DeviceActionResult),
        "device.setSceneBypassBehavior" => Some(GatewayResultKind::DeviceActionResult),
        "device.setMasterVolumeAssignment" => Some(GatewayResultKind::DeviceActionResult),
        "device.setGlobalBypass" => Some(GatewayResultKind::DeviceActionResult),
        "device.presetScreenshot" => Some(GatewayResultKind::Object),
        "device.captureScreen" => Some(GatewayResultKind::Object),
        "device.graphicsTree" => Some(GatewayResultKind::Object),
        "device.tapScreen" => Some(GatewayResultKind::DeviceActionResult),
        "device.swipeScreen" => Some(GatewayResultKind::DeviceActionResult),
        "device.selectScene" => Some(GatewayResultKind::DeviceActionResult),
        "device.copyScene" => Some(GatewayResultKind::DeviceActionResult),
        "device.setSceneLabel" => Some(GatewayResultKind::DeviceActionResult),
        "device.setSceneColor" => Some(GatewayResultKind::DeviceActionResult),
        "device.toggleBypass" => Some(GatewayResultKind::DeviceActionResult),
        "device.moveBlock" => Some(GatewayResultKind::DeviceActionResult),
        "device.addBlock" => Some(GatewayResultKind::DeviceActionResult),
        "device.removeBlock" => Some(GatewayResultKind::DeviceActionResult),
        "device.setBlockFootswitch" => Some(GatewayResultKind::DeviceActionResult),
        "device.setStompMomentary" => Some(GatewayResultKind::DeviceActionResult),
        "device.setStompLabel" => Some(GatewayResultKind::DeviceActionResult),
        "device.setMidiOut" => Some(GatewayResultKind::DeviceActionResult),
        "device.setPresetLoadMidiOut" => Some(GatewayResultKind::DeviceActionResult),
        "device.setExpressionBypass" => Some(GatewayResultKind::DeviceActionResult),
        "device.setChainInput" => Some(GatewayResultKind::DeviceActionResult),
        "device.setChainOutput" => Some(GatewayResultKind::DeviceActionResult),
        "device.setChainSplit" => Some(GatewayResultKind::DeviceActionResult),
        "device.setSplitMute" => Some(GatewayResultKind::DeviceActionResult),
        "device.listPresets" => Some(GatewayResultKind::Object),
        "device.listPresetFolders" => Some(GatewayResultKind::Object),
        "device.navigateBank" => Some(GatewayResultKind::DeviceActionResult),
        "device.recallPreset" => Some(GatewayResultKind::DeviceActionResult),
        "device.reloadPreset" => Some(GatewayResultKind::DeviceActionResult),
        "device.blockDetails" => Some(GatewayResultKind::Object),
        "device.laneControlDetails" => Some(GatewayResultKind::Object),
        "device.previewParameter" => Some(GatewayResultKind::Object),
        "device.previewLaneControlParameter" => Some(GatewayResultKind::Object),
        "device.setParameter" => Some(GatewayResultKind::DeviceActionResult),
        "device.setLaneControlParameter" => Some(GatewayResultKind::DeviceActionResult),
        "device.setLaneControlSceneMode" => Some(GatewayResultKind::DeviceActionResult),
        "device.setParameterSceneMode" => Some(GatewayResultKind::DeviceActionResult),
        "device.setParameterExpression" => Some(GatewayResultKind::DeviceActionResult),
        "device.setTempo" => Some(GatewayResultKind::DeviceActionResult),
        "device.setMasterVolume" => Some(GatewayResultKind::DeviceActionResult),
        "device.masterVolume" => Some(GatewayResultKind::Object),
        "device.pressFootswitch" => Some(GatewayResultKind::DeviceActionResult),
        "device.tapTempo" => Some(GatewayResultKind::DeviceActionResult),
        "device.selectModeSlot" => Some(GatewayResultKind::DeviceActionResult),
        "device.listPresetSlots" => Some(GatewayResultKind::Object),
        "device.savePresetAs" => Some(GatewayResultKind::DeviceActionResult),
        "device.copyPreset" => Some(GatewayResultKind::DeviceActionResult),
        "device.renameCurrentPreset" => Some(GatewayResultKind::DeviceActionResult),
        "device.createBackup" => Some(GatewayResultKind::Object),
        "device.showTuner" => Some(GatewayResultKind::DeviceActionResult),
        "device.showGigView" => Some(GatewayResultKind::DeviceActionResult),
        _ => None,
    }
}

pub fn validate_result(method: &str, result: &serde_json::Value) -> Result<(), String> {
    let result_kind =
        result_kind(method).ok_or_else(|| format!("Unknown gateway result contract: {method}"))?;
    let object = result
        .as_object()
        .ok_or_else(|| format!("{method} returned a malformed result"))?;
    if result_kind == GatewayResultKind::PresetSnapshot
        && (!object
            .get("presetName")
            .is_some_and(serde_json::Value::is_string)
            || !object
                .get("blocks")
                .is_some_and(serde_json::Value::is_array))
    {
        return Err(format!(
            "{method} returned a malformed PresetSnapshot result"
        ));
    }
    let has_outcome = ["accepted", "verified", "verification"]
        .iter()
        .any(|key| object.contains_key(*key));
    if result_kind == GatewayResultKind::DeviceActionResult && !has_outcome {
        return Err(format!(
            "{method} returned a device action result without verification semantics"
        ));
    }
    if has_outcome {
        let verified = object.get("verified").and_then(serde_json::Value::as_bool);
        let expected = if verified == Some(true) {
            "authoritative_readback"
        } else {
            "accepted_unverified"
        };
        if object.get("accepted").and_then(serde_json::Value::as_bool) != Some(true)
            || verified.is_none()
            || object
                .get("verification")
                .and_then(serde_json::Value::as_str)
                != Some(expected)
            || object
                .get("detail")
                .and_then(serde_json::Value::as_str)
                .is_none_or(|detail| detail.chars().count() > 4096)
        {
            return Err(format!(
                "{method} returned a malformed device action result"
            ));
        }
    }
    Ok(())
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BrokerDispatch {
    SystemStatus,
    Reconnect,
    ResetSession,
    Disconnect,
    Snapshot,
    StateEvents,
    TempoClock,
    ListModels,
    Identity,
    SetDeviceName,
    Undo,
    Redo,
    InhibitedModules,
    GatewayRead,
    GatewayOperation,
    PresetScreenshot,
    CaptureScreen,
    TapScreen,
    SelectScene,
    ToggleBypass,
    BlockDetails,
    LaneControlDetails,
    PreviewParameter,
    PreviewLaneControlParameter,
    SetParameter,
    SetLaneControlParameter,
    SetLaneControlSceneMode,
    ParameterAssignment,
    SetTempo,
    SetMasterVolume,
    MasterVolume,
    PerformanceMidi,
    ListPresets,
    ListPresetFolders,
    NavigateBank,
    RecallPreset,
    ReloadPreset,
    ListPresetSlots,
    SavePresetAs,
    CopyPreset,
    RenameCurrentPreset,
    CreateBackup,
    DuplicateSetlist,
}

pub fn broker_dispatch(method: &str) -> Option<BrokerDispatch> {
    match method {
        "system.status" => Some(BrokerDispatch::SystemStatus),
        "device.reconnect" => Some(BrokerDispatch::Reconnect),
        "device.resetSession" => Some(BrokerDispatch::ResetSession),
        "device.disconnect" => Some(BrokerDispatch::Disconnect),
        "device.snapshot" => Some(BrokerDispatch::Snapshot),
        "device.stateEvents" => Some(BrokerDispatch::StateEvents),
        "device.tempoClock" => Some(BrokerDispatch::TempoClock),
        "device.listModels" => Some(BrokerDispatch::ListModels),
        "device.identity" => Some(BrokerDispatch::Identity),
        "device.setDeviceName" => Some(BrokerDispatch::SetDeviceName),
        "device.undo" => Some(BrokerDispatch::Undo),
        "device.redo" => Some(BrokerDispatch::Redo),
        "device.inhibitedModules" => Some(BrokerDispatch::InhibitedModules),
        "device.tunerSettings" => Some(BrokerDispatch::GatewayRead),
        "device.setTunerInput" => Some(BrokerDispatch::GatewayOperation),
        "device.setTunerMute" => Some(BrokerDispatch::GatewayOperation),
        "device.restoreTunerAudio" => Some(BrokerDispatch::GatewayOperation),
        "device.setTunerReference" => Some(BrokerDispatch::GatewayOperation),
        "device.setTunerMeter" => Some(BrokerDispatch::GatewayOperation),
        "device.generalSettings" => Some(BrokerDispatch::GatewayRead),
        "device.ioSettings" => Some(BrokerDispatch::GatewayRead),
        "device.setInputPort" => Some(BrokerDispatch::GatewayOperation),
        "device.setOutputPort" => Some(BrokerDispatch::GatewayOperation),
        "device.setUsbPort" => Some(BrokerDispatch::GatewayOperation),
        "device.setMidiThru" => Some(BrokerDispatch::GatewayOperation),
        "device.setOutputPairing" => Some(BrokerDispatch::GatewayOperation),
        "device.globalEq" => Some(BrokerDispatch::GatewayRead),
        "device.setGlobalEqBypassed" => Some(BrokerDispatch::GatewayOperation),
        "device.setGlobalEqBand" => Some(BrokerDispatch::GatewayOperation),
        "device.setGlobalEqOutput" => Some(BrokerDispatch::GatewayOperation),
        "device.modeCycle" => Some(BrokerDispatch::GatewayRead),
        "device.setModeCycle" => Some(BrokerDispatch::GatewayOperation),
        "device.globalTempoSettings" => Some(BrokerDispatch::GatewayRead),
        "device.setTempoMetronome" => Some(BrokerDispatch::GatewayOperation),
        "device.setTempoMode" => Some(BrokerDispatch::GatewayOperation),
        "device.setGlobalTempo" => Some(BrokerDispatch::GatewayOperation),
        "device.looperStatus" => Some(BrokerDispatch::GatewayRead),
        "device.controlLooper" => Some(BrokerDispatch::PerformanceMidi),
        "device.recents" => Some(BrokerDispatch::GatewayRead),
        "device.favorites" => Some(BrokerDispatch::GatewayRead),
        "device.setFavorite" => Some(BrokerDispatch::GatewayOperation),
        "device.pinnedModels" => Some(BrokerDispatch::GatewayRead),
        "device.setModelPinned" => Some(BrokerDispatch::GatewayOperation),
        "device.captures" => Some(BrokerDispatch::GatewayRead),
        "device.loadCapture" => Some(BrokerDispatch::GatewayOperation),
        "device.irs" => Some(BrokerDispatch::GatewayRead),
        "device.loadIr" => Some(BrokerDispatch::GatewayOperation),
        "device.createSetlist" => Some(BrokerDispatch::GatewayOperation),
        "device.deleteSetlist" => Some(BrokerDispatch::GatewayOperation),
        "device.duplicateSetlist" => Some(BrokerDispatch::DuplicateSetlist),
        "device.deletePreset" => Some(BrokerDispatch::GatewayOperation),
        "device.movePreset" => Some(BrokerDispatch::GatewayOperation),
        "device.setGeneralInteger" => Some(BrokerDispatch::GatewayOperation),
        "device.setGeneralToggle" => Some(BrokerDispatch::GatewayOperation),
        "device.setSceneBypassBehavior" => Some(BrokerDispatch::GatewayOperation),
        "device.setMasterVolumeAssignment" => Some(BrokerDispatch::GatewayOperation),
        "device.setGlobalBypass" => Some(BrokerDispatch::GatewayOperation),
        "device.presetScreenshot" => Some(BrokerDispatch::PresetScreenshot),
        "device.captureScreen" => Some(BrokerDispatch::CaptureScreen),
        "device.graphicsTree" => Some(BrokerDispatch::GatewayRead),
        "device.tapScreen" => Some(BrokerDispatch::TapScreen),
        "device.swipeScreen" => Some(BrokerDispatch::TapScreen),
        "device.selectScene" => Some(BrokerDispatch::SelectScene),
        "device.copyScene" => Some(BrokerDispatch::GatewayOperation),
        "device.setSceneLabel" => Some(BrokerDispatch::GatewayOperation),
        "device.setSceneColor" => Some(BrokerDispatch::GatewayOperation),
        "device.toggleBypass" => Some(BrokerDispatch::ToggleBypass),
        "device.moveBlock" => Some(BrokerDispatch::GatewayOperation),
        "device.addBlock" => Some(BrokerDispatch::GatewayOperation),
        "device.removeBlock" => Some(BrokerDispatch::GatewayOperation),
        "device.setBlockFootswitch" => Some(BrokerDispatch::GatewayOperation),
        "device.setStompMomentary" => Some(BrokerDispatch::GatewayOperation),
        "device.setStompLabel" => Some(BrokerDispatch::GatewayOperation),
        "device.setMidiOut" => Some(BrokerDispatch::GatewayOperation),
        "device.setPresetLoadMidiOut" => Some(BrokerDispatch::GatewayOperation),
        "device.setExpressionBypass" => Some(BrokerDispatch::GatewayOperation),
        "device.setChainInput" => Some(BrokerDispatch::GatewayOperation),
        "device.setChainOutput" => Some(BrokerDispatch::GatewayOperation),
        "device.setChainSplit" => Some(BrokerDispatch::GatewayOperation),
        "device.setSplitMute" => Some(BrokerDispatch::GatewayOperation),
        "device.listPresets" => Some(BrokerDispatch::ListPresets),
        "device.listPresetFolders" => Some(BrokerDispatch::ListPresetFolders),
        "device.navigateBank" => Some(BrokerDispatch::NavigateBank),
        "device.recallPreset" => Some(BrokerDispatch::RecallPreset),
        "device.reloadPreset" => Some(BrokerDispatch::ReloadPreset),
        "device.blockDetails" => Some(BrokerDispatch::BlockDetails),
        "device.laneControlDetails" => Some(BrokerDispatch::LaneControlDetails),
        "device.previewParameter" => Some(BrokerDispatch::PreviewParameter),
        "device.previewLaneControlParameter" => Some(BrokerDispatch::PreviewLaneControlParameter),
        "device.setParameter" => Some(BrokerDispatch::SetParameter),
        "device.setLaneControlParameter" => Some(BrokerDispatch::SetLaneControlParameter),
        "device.setLaneControlSceneMode" => Some(BrokerDispatch::SetLaneControlSceneMode),
        "device.setParameterSceneMode" => Some(BrokerDispatch::ParameterAssignment),
        "device.setParameterExpression" => Some(BrokerDispatch::ParameterAssignment),
        "device.setTempo" => Some(BrokerDispatch::SetTempo),
        "device.setMasterVolume" => Some(BrokerDispatch::SetMasterVolume),
        "device.masterVolume" => Some(BrokerDispatch::MasterVolume),
        "device.pressFootswitch" => Some(BrokerDispatch::PerformanceMidi),
        "device.tapTempo" => Some(BrokerDispatch::PerformanceMidi),
        "device.selectModeSlot" => Some(BrokerDispatch::PerformanceMidi),
        "device.listPresetSlots" => Some(BrokerDispatch::ListPresetSlots),
        "device.savePresetAs" => Some(BrokerDispatch::SavePresetAs),
        "device.copyPreset" => Some(BrokerDispatch::CopyPreset),
        "device.renameCurrentPreset" => Some(BrokerDispatch::RenameCurrentPreset),
        "device.createBackup" => Some(BrokerDispatch::CreateBackup),
        "device.showTuner" => Some(BrokerDispatch::PerformanceMidi),
        "device.showGigView" => Some(BrokerDispatch::PerformanceMidi),
        _ => None,
    }
}

pub fn validate_params(method: &str, params: &serde_json::Value) -> Result<(), String> {
    let object = match params {
        serde_json::Value::Null => None,
        serde_json::Value::Object(object) => Some(object),
        _ => return Err("JSON-RPC params must be an object".into()),
    };
    let (allowed, required): (&[&str], &[&str]) = match method {
        "system.status" => (&[], &[]),
        "device.reconnect" => (&[], &[]),
        "device.resetSession" => (&[], &[]),
        "device.disconnect" => (&[], &[]),
        "device.snapshot" => (&[], &[]),
        "device.stateEvents" => (&["afterSequence", "limit"], &[]),
        "device.tempoClock" => (&[], &[]),
        "device.listModels" => (&[], &[]),
        "device.identity" => (&[], &[]),
        "device.setDeviceName" => (&["name"], &["name"]),
        "device.undo" => (&[], &[]),
        "device.redo" => (&[], &[]),
        "device.inhibitedModules" => (&[], &[]),
        "device.tunerSettings" => (&[], &[]),
        "device.setTunerInput" => (
            &["inputPortId", "confirmTunerActivation"],
            &["inputPortId", "confirmTunerActivation"],
        ),
        "device.setTunerMute" => (
            &["muted", "confirmTunerActivation"],
            &["muted", "confirmTunerActivation"],
        ),
        "device.restoreTunerAudio" => (&["confirmPreferenceReset"], &["confirmPreferenceReset"]),
        "device.setTunerReference" => (
            &["referenceOffsetHz", "confirmTunerActivation"],
            &["referenceOffsetHz", "confirmTunerActivation"],
        ),
        "device.setTunerMeter" => (
            &["enabled", "confirmTunerActivation"],
            &["enabled", "confirmTunerActivation"],
        ),
        "device.generalSettings" => (&[], &[]),
        "device.ioSettings" => (&[], &[]),
        "device.setInputPort" => (
            &[
                "inputPortId",
                "levelDb",
                "impedance",
                "inputType",
                "groundLift",
            ],
            &[
                "inputPortId",
                "levelDb",
                "impedance",
                "inputType",
                "groundLift",
            ],
        ),
        "device.setOutputPort" => (
            &["outputPortId", "level", "groundLift", "mute"],
            &["outputPortId", "level", "groundLift", "mute"],
        ),
        "device.setUsbPort" => (
            &["level", "headphonesSource", "dryWet"],
            &["level", "headphonesSource", "dryWet"],
        ),
        "device.setMidiThru" => (&["enabled"], &["enabled"]),
        "device.setOutputPairing" => (
            &["xlr12Linked", "out34Linked"],
            &["xlr12Linked", "out34Linked"],
        ),
        "device.globalEq" => (&[], &[]),
        "device.setGlobalEqBypassed" => (&["bypassed"], &["bypassed"]),
        "device.setGlobalEqBand" => (
            &["band", "gain", "frequency", "q", "filterType", "enabled"],
            &["band", "gain", "frequency", "q", "filterType", "enabled"],
        ),
        "device.setGlobalEqOutput" => (&["level", "out12", "out34"], &["level", "out12", "out34"]),
        "device.modeCycle" => (&[], &[]),
        "device.setModeCycle" => (&["slots"], &["slots"]),
        "device.globalTempoSettings" => (&[], &[]),
        "device.setTempoMetronome" => (
            &[
                "ledEnabled",
                "volumeDb",
                "running",
                "pan",
                "timeSignature",
                "subdivision",
                "sound",
                "routing",
                "beats",
            ],
            &[
                "ledEnabled",
                "volumeDb",
                "running",
                "pan",
                "timeSignature",
                "subdivision",
                "sound",
                "routing",
                "beats",
            ],
        ),
        "device.setTempoMode" => (&["mode"], &["mode"]),
        "device.setGlobalTempo" => (
            &["bpm", "expectedMode", "expectedGlobalBpm"],
            &["bpm", "expectedMode", "expectedGlobalBpm"],
        ),
        "device.looperStatus" => (&[], &[]),
        "device.controlLooper" => (&["command", "value"], &["command", "value"]),
        "device.recents" => (&[], &[]),
        "device.favorites" => (&[], &[]),
        "device.setFavorite" => (
            &["name", "folderKey", "folderName", "isFactory", "favorite"],
            &["name", "folderKey", "folderName", "isFactory", "favorite"],
        ),
        "device.pinnedModels" => (&[], &[]),
        "device.setModelPinned" => (&["modelId", "pinned"], &["modelId", "pinned"]),
        "device.captures" => (&[], &[]),
        "device.loadCapture" => (
            &[
                "row",
                "column",
                "key",
                "name",
                "modelId",
                "expectedModelId",
                "expectedPresetName",
            ],
            &["row", "column", "key", "name", "modelId", "expectedModelId"],
        ),
        "device.irs" => (&["folder"], &["folder"]),
        "device.loadIr" => (
            &[
                "row",
                "column",
                "key",
                "name",
                "slot",
                "modelId",
                "expectedModelId",
                "expectedPresetName",
            ],
            &[
                "row",
                "column",
                "key",
                "name",
                "slot",
                "modelId",
                "expectedModelId",
            ],
        ),
        "device.createSetlist" => (&["name"], &["name"]),
        "device.deleteSetlist" => (&["name"], &["name"]),
        "device.duplicateSetlist" => (
            &[
                "sourceSetlistKey",
                "destinationName",
                "limit",
                "expectedPresetName",
                "expectedPosition",
            ],
            &[
                "sourceSetlistKey",
                "destinationName",
                "limit",
                "expectedPosition",
            ],
        ),
        "device.deletePreset" => (&["setlistKey", "name"], &["setlistKey", "name"]),
        "device.movePreset" => (
            &["setlistKey", "name", "position"],
            &["setlistKey", "name", "position"],
        ),
        "device.setGeneralInteger" => (&["setting", "value"], &["setting", "value"]),
        "device.setGeneralToggle" => (&["setting", "enabled"], &["setting", "enabled"]),
        "device.setSceneBypassBehavior" => (&["behavior"], &["behavior"]),
        "device.setMasterVolumeAssignment" => (
            &["out12", "out34", "send12", "headphones"],
            &["out12", "out34", "send12", "headphones"],
        ),
        "device.setGlobalBypass" => (&["cab", "ir"], &["cab", "ir"]),
        "device.presetScreenshot" => (
            &["folderName", "position", "isFactory"],
            &["folderName", "position"],
        ),
        "device.captureScreen" => (&[], &[]),
        "device.graphicsTree" => (&[], &[]),
        "device.tapScreen" => (&["x", "y"], &["x", "y"]),
        "device.swipeScreen" => (&["x", "y", "toX", "toY"], &["x", "y", "toX", "toY"]),
        "device.selectScene" => (&["scene", "expectedPresetName"], &["scene"]),
        "device.copyScene" => (
            &["fromScene", "toScene", "swap", "expectedPresetName"],
            &["fromScene", "toScene"],
        ),
        "device.setSceneLabel" => (
            &["scene", "label", "expectedPresetName"],
            &["scene", "label"],
        ),
        "device.setSceneColor" => (
            &["scene", "color", "expectedPresetName"],
            &["scene", "color"],
        ),
        "device.toggleBypass" => (
            &[
                "row",
                "column",
                "expectedScene",
                "expectedBypassed",
                "desiredBypassed",
                "expectedPresetName",
            ],
            &[
                "row",
                "column",
                "expectedScene",
                "expectedBypassed",
                "desiredBypassed",
            ],
        ),
        "device.moveBlock" => (
            &[
                "row",
                "fromColumn",
                "toColumn",
                "expectedModelId",
                "expectedPresetName",
            ],
            &["row", "fromColumn", "toColumn", "expectedModelId"],
        ),
        "device.addBlock" => (
            &["row", "column", "modelId", "expectedPresetName"],
            &["row", "column", "modelId"],
        ),
        "device.removeBlock" => (
            &["row", "column", "expectedModelId", "expectedPresetName"],
            &["row", "column", "expectedModelId"],
        ),
        "device.setBlockFootswitch" => (
            &[
                "row",
                "column",
                "footswitch",
                "expectedFootswitch",
                "expectedModelId",
                "expectedPresetName",
            ],
            &[
                "row",
                "column",
                "footswitch",
                "expectedFootswitch",
                "expectedModelId",
            ],
        ),
        "device.setStompMomentary" => (
            &["footswitch", "momentary", "expectedPresetName"],
            &["footswitch", "momentary"],
        ),
        "device.setStompLabel" => (
            &["footswitch", "label", "expectedPresetName"],
            &["footswitch", "label"],
        ),
        "device.setMidiOut" => (
            &["source", "messages", "expectedPresetName"],
            &["source", "messages"],
        ),
        "device.setPresetLoadMidiOut" => (&["messages", "expectedPresetName"], &["messages"]),
        "device.setExpressionBypass" => (
            &[
                "row",
                "column",
                "pedal",
                "mode",
                "invert",
                "delayMs",
                "latchEmulation",
                "expectedPresetName",
            ],
            &[
                "row",
                "column",
                "pedal",
                "mode",
                "invert",
                "delayMs",
                "latchEmulation",
            ],
        ),
        "device.setChainInput" => (
            &["row", "inputId", "expectedInputId", "expectedPresetName"],
            &["row", "inputId", "expectedInputId"],
        ),
        "device.setChainOutput" => (
            &["row", "outputId", "expectedOutputId", "expectedPresetName"],
            &["row", "outputId", "expectedOutputId"],
        ),
        "device.setChainSplit" => (
            &[
                "row",
                "splitColumn",
                "mixColumn",
                "expectedSplitColumn",
                "expectedMixColumn",
                "expectedPresetName",
            ],
            &[
                "row",
                "splitColumn",
                "mixColumn",
                "expectedSplitColumn",
                "expectedMixColumn",
            ],
        ),
        "device.setSplitMute" => (
            &["row", "muted", "expectedMuted", "expectedPresetName"],
            &["row", "muted", "expectedMuted"],
        ),
        "device.listPresets" => (&["refresh", "setlistKey"], &["setlistKey"]),
        "device.listPresetFolders" => (&["refresh"], &[]),
        "device.navigateBank" => (
            &["direction", "expectedPresetName", "expectedPosition"],
            &["direction", "expectedPosition"],
        ),
        "device.recallPreset" => (
            &[
                "setlistKey",
                "position",
                "expectedPresetName",
                "expectedPosition",
                "expectedSetlistKey",
            ],
            &[
                "setlistKey",
                "position",
                "expectedPosition",
                "expectedSetlistKey",
            ],
        ),
        "device.reloadPreset" => (
            &["expectedPresetName", "expectedPosition"],
            &["expectedPosition"],
        ),
        "device.blockDetails" => (&["row", "column", "expectedPresetName"], &["row", "column"]),
        "device.laneControlDetails" => (
            &["row", "control", "expectedPresetName"],
            &["row", "control"],
        ),
        "device.previewParameter" => (
            &[
                "row",
                "column",
                "parameterIndex",
                "value",
                "expectedValue",
                "expectedScene",
                "expectedPresetName",
            ],
            &[
                "row",
                "column",
                "parameterIndex",
                "value",
                "expectedValue",
                "expectedScene",
            ],
        ),
        "device.previewLaneControlParameter" => (
            &[
                "row",
                "control",
                "parameterIndex",
                "value",
                "expectedValue",
                "expectedPresetName",
            ],
            &["row", "control", "parameterIndex", "value", "expectedValue"],
        ),
        "device.setParameter" => (
            &[
                "row",
                "column",
                "parameterIndex",
                "value",
                "expectedValue",
                "expectedScene",
                "expectedPresetName",
            ],
            &[
                "row",
                "column",
                "parameterIndex",
                "value",
                "expectedValue",
                "expectedScene",
            ],
        ),
        "device.setLaneControlParameter" => (
            &[
                "row",
                "control",
                "parameterIndex",
                "value",
                "expectedValue",
                "expectedPresetName",
            ],
            &["row", "control", "parameterIndex", "value", "expectedValue"],
        ),
        "device.setLaneControlSceneMode" => (
            &[
                "row",
                "control",
                "parameterIndex",
                "enabled",
                "expectedPresetName",
            ],
            &["row", "control", "parameterIndex", "enabled"],
        ),
        "device.setParameterSceneMode" => (
            &[
                "row",
                "column",
                "parameterIndex",
                "enabled",
                "expectedPresetName",
            ],
            &["row", "column", "parameterIndex", "enabled"],
        ),
        "device.setParameterExpression" => (
            &[
                "row",
                "column",
                "parameterIndex",
                "pedal",
                "minimum",
                "maximum",
                "expectedPresetName",
            ],
            &[
                "row",
                "column",
                "parameterIndex",
                "pedal",
                "minimum",
                "maximum",
            ],
        ),
        "device.setTempo" => (
            &["bpm", "expectedTempo", "expectedPresetName"],
            &["bpm", "expectedTempo"],
        ),
        "device.setMasterVolume" => (&["value", "expectedValue"], &["value", "expectedValue"]),
        "device.masterVolume" => (&[], &[]),
        "device.pressFootswitch" => (
            &["index", "expectedMode", "expectedPresetName"],
            &["index", "expectedMode"],
        ),
        "device.tapTempo" => (&["expectedMode", "expectedPresetName"], &["expectedMode"]),
        "device.selectModeSlot" => (&["slot", "expectedPresetName"], &["slot"]),
        "device.listPresetSlots" => (&[], &[]),
        "device.savePresetAs" => (
            &[
                "setlistKey",
                "position",
                "name",
                "expectedPresetName",
                "expectedPosition",
                "confirmOverwrite",
            ],
            &["setlistKey", "position", "name", "expectedPosition"],
        ),
        "device.copyPreset" => (
            &[
                "sourceSetlistKey",
                "sourcePosition",
                "sourceName",
                "destinationSetlistKey",
                "destinationPosition",
                "expectedPresetName",
                "expectedPosition",
                "confirmOverwrite",
            ],
            &[
                "sourceSetlistKey",
                "sourcePosition",
                "destinationSetlistKey",
                "destinationPosition",
                "expectedPosition",
            ],
        ),
        "device.renameCurrentPreset" => (
            &[
                "name",
                "expectedPresetName",
                "expectedPosition",
                "confirmRename",
            ],
            &["name", "expectedPosition"],
        ),
        "device.createBackup" => (&["name"], &[]),
        "device.showTuner" => (&["shown"], &[]),
        "device.showGigView" => (&["shown"], &[]),
        _ => return Err(format!("Method not found: {method}")),
    };
    let supplied = object.map(|value| value.keys()).into_iter().flatten();
    for key in supplied {
        if !allowed.contains(&key.as_str()) {
            return Err(format!("unexpected argument for {method}: {key}"));
        }
    }
    for key in required {
        if !object.is_some_and(|value| value.contains_key(*key)) {
            return Err(format!("missing required argument for {method}: {key}"));
        }
    }
    if let Some(object) = object {
        let kinds: &[(&str, &str)] = match method {
            "system.status" => &[],
            "device.reconnect" => &[],
            "device.resetSession" => &[],
            "device.disconnect" => &[],
            "device.snapshot" => &[],
            "device.stateEvents" => &[("afterSequence", "integer"), ("limit", "integer")],
            "device.tempoClock" => &[],
            "device.listModels" => &[],
            "device.identity" => &[],
            "device.setDeviceName" => &[("name", "string")],
            "device.undo" => &[],
            "device.redo" => &[],
            "device.inhibitedModules" => &[],
            "device.tunerSettings" => &[],
            "device.setTunerInput" => &[
                ("inputPortId", "integer"),
                ("confirmTunerActivation", "boolean"),
            ],
            "device.setTunerMute" => &[("muted", "boolean"), ("confirmTunerActivation", "boolean")],
            "device.restoreTunerAudio" => &[("confirmPreferenceReset", "boolean")],
            "device.setTunerReference" => &[
                ("referenceOffsetHz", "number"),
                ("confirmTunerActivation", "boolean"),
            ],
            "device.setTunerMeter" => &[
                ("enabled", "boolean"),
                ("confirmTunerActivation", "boolean"),
            ],
            "device.generalSettings" => &[],
            "device.ioSettings" => &[],
            "device.setInputPort" => &[
                ("inputPortId", "integer"),
                ("levelDb", "nullable-number"),
                ("impedance", "nullable-number"),
                ("inputType", "nullable-number"),
                ("groundLift", "nullable-number"),
            ],
            "device.setOutputPort" => &[
                ("outputPortId", "integer"),
                ("level", "nullable-number"),
                ("groundLift", "nullable-number"),
                ("mute", "nullable-boolean"),
            ],
            "device.setUsbPort" => &[
                ("level", "nullable-number"),
                ("headphonesSource", "nullable-number"),
                ("dryWet", "nullable-number"),
            ],
            "device.setMidiThru" => &[("enabled", "boolean")],
            "device.setOutputPairing" => &[
                ("xlr12Linked", "nullable-boolean"),
                ("out34Linked", "nullable-boolean"),
            ],
            "device.globalEq" => &[],
            "device.setGlobalEqBypassed" => &[("bypassed", "boolean")],
            "device.setGlobalEqBand" => &[
                ("band", "integer"),
                ("gain", "nullable-number"),
                ("frequency", "nullable-number"),
                ("q", "nullable-number"),
                ("filterType", "nullable-integer"),
                ("enabled", "nullable-boolean"),
            ],
            "device.setGlobalEqOutput" => &[
                ("level", "nullable-number"),
                ("out12", "nullable-boolean"),
                ("out34", "nullable-boolean"),
            ],
            "device.modeCycle" => &[],
            "device.setModeCycle" => &[("slots", "array")],
            "device.globalTempoSettings" => &[],
            "device.setTempoMetronome" => &[
                ("ledEnabled", "nullable-boolean"),
                ("volumeDb", "nullable-number"),
                ("running", "nullable-boolean"),
                ("pan", "nullable-number"),
                ("timeSignature", "nullable-string"),
                ("subdivision", "nullable-string"),
                ("sound", "nullable-string"),
                ("routing", "nullable-string"),
                ("beats", "nullable-array"),
            ],
            "device.setTempoMode" => &[("mode", "string")],
            "device.setGlobalTempo" => &[
                ("bpm", "integer"),
                ("expectedMode", "string"),
                ("expectedGlobalBpm", "integer"),
            ],
            "device.looperStatus" => &[],
            "device.controlLooper" => &[("command", "string"), ("value", "nullable-integer")],
            "device.recents" => &[],
            "device.favorites" => &[],
            "device.setFavorite" => &[
                ("name", "string"),
                ("folderKey", "string"),
                ("folderName", "string"),
                ("isFactory", "boolean"),
                ("favorite", "boolean"),
            ],
            "device.pinnedModels" => &[],
            "device.setModelPinned" => &[("modelId", "integer"), ("pinned", "boolean")],
            "device.captures" => &[],
            "device.loadCapture" => &[
                ("row", "integer"),
                ("column", "integer"),
                ("key", "string"),
                ("name", "string"),
                ("modelId", "nullable-integer"),
                ("expectedModelId", "nullable-integer"),
                ("expectedPresetName", "string"),
            ],
            "device.irs" => &[("folder", "nullable-string")],
            "device.loadIr" => &[
                ("row", "integer"),
                ("column", "integer"),
                ("key", "string"),
                ("name", "string"),
                ("slot", "integer"),
                ("modelId", "nullable-integer"),
                ("expectedModelId", "nullable-integer"),
                ("expectedPresetName", "string"),
            ],
            "device.createSetlist" => &[("name", "string")],
            "device.deleteSetlist" => &[("name", "string")],
            "device.duplicateSetlist" => &[
                ("sourceSetlistKey", "string"),
                ("destinationName", "string"),
                ("limit", "nullable-integer"),
                ("expectedPresetName", "string"),
                ("expectedPosition", "integer"),
            ],
            "device.deletePreset" => &[("setlistKey", "string"), ("name", "string")],
            "device.movePreset" => &[
                ("setlistKey", "string"),
                ("name", "string"),
                ("position", "integer"),
            ],
            "device.setGeneralInteger" => &[("setting", "string"), ("value", "integer")],
            "device.setGeneralToggle" => &[("setting", "string"), ("enabled", "boolean")],
            "device.setSceneBypassBehavior" => &[("behavior", "string")],
            "device.setMasterVolumeAssignment" => &[
                ("out12", "boolean"),
                ("out34", "boolean"),
                ("send12", "boolean"),
                ("headphones", "boolean"),
            ],
            "device.setGlobalBypass" => &[("cab", "array"), ("ir", "array")],
            "device.presetScreenshot" => &[
                ("folderName", "string"),
                ("position", "integer"),
                ("isFactory", "boolean"),
            ],
            "device.captureScreen" => &[],
            "device.graphicsTree" => &[],
            "device.tapScreen" => &[("x", "integer"), ("y", "integer")],
            "device.swipeScreen" => &[
                ("x", "integer"),
                ("y", "integer"),
                ("toX", "integer"),
                ("toY", "integer"),
            ],
            "device.selectScene" => &[("scene", "integer"), ("expectedPresetName", "string")],
            "device.copyScene" => &[
                ("fromScene", "integer"),
                ("toScene", "integer"),
                ("swap", "boolean"),
                ("expectedPresetName", "string"),
            ],
            "device.setSceneLabel" => &[
                ("scene", "integer"),
                ("label", "nullable-string"),
                ("expectedPresetName", "string"),
            ],
            "device.setSceneColor" => &[
                ("scene", "integer"),
                ("color", "integer"),
                ("expectedPresetName", "string"),
            ],
            "device.toggleBypass" => &[
                ("row", "integer"),
                ("column", "integer"),
                ("expectedScene", "integer"),
                ("expectedBypassed", "boolean"),
                ("desiredBypassed", "boolean"),
                ("expectedPresetName", "string"),
            ],
            "device.moveBlock" => &[
                ("row", "integer"),
                ("fromColumn", "integer"),
                ("toColumn", "integer"),
                ("expectedModelId", "integer"),
                ("expectedPresetName", "string"),
            ],
            "device.addBlock" => &[
                ("row", "integer"),
                ("column", "integer"),
                ("modelId", "integer"),
                ("expectedPresetName", "string"),
            ],
            "device.removeBlock" => &[
                ("row", "integer"),
                ("column", "integer"),
                ("expectedModelId", "integer"),
                ("expectedPresetName", "string"),
            ],
            "device.setBlockFootswitch" => &[
                ("row", "integer"),
                ("column", "integer"),
                ("footswitch", "nullable-integer"),
                ("expectedFootswitch", "nullable-integer"),
                ("expectedModelId", "integer"),
                ("expectedPresetName", "string"),
            ],
            "device.setStompMomentary" => &[
                ("footswitch", "integer"),
                ("momentary", "boolean"),
                ("expectedPresetName", "string"),
            ],
            "device.setStompLabel" => &[
                ("footswitch", "integer"),
                ("label", "string"),
                ("expectedPresetName", "string"),
            ],
            "device.setMidiOut" => &[
                ("source", "integer"),
                ("messages", "array"),
                ("expectedPresetName", "string"),
            ],
            "device.setPresetLoadMidiOut" => {
                &[("messages", "array"), ("expectedPresetName", "string")]
            }
            "device.setExpressionBypass" => &[
                ("row", "integer"),
                ("column", "integer"),
                ("pedal", "integer"),
                ("mode", "integer"),
                ("invert", "boolean"),
                ("delayMs", "integer"),
                ("latchEmulation", "boolean"),
                ("expectedPresetName", "string"),
            ],
            "device.setChainInput" => &[
                ("row", "integer"),
                ("inputId", "integer"),
                ("expectedInputId", "integer"),
                ("expectedPresetName", "string"),
            ],
            "device.setChainOutput" => &[
                ("row", "integer"),
                ("outputId", "integer"),
                ("expectedOutputId", "integer"),
                ("expectedPresetName", "string"),
            ],
            "device.setChainSplit" => &[
                ("row", "integer"),
                ("splitColumn", "nullable-integer"),
                ("mixColumn", "nullable-integer"),
                ("expectedSplitColumn", "nullable-integer"),
                ("expectedMixColumn", "nullable-integer"),
                ("expectedPresetName", "string"),
            ],
            "device.setSplitMute" => &[
                ("row", "integer"),
                ("muted", "boolean"),
                ("expectedMuted", "boolean"),
                ("expectedPresetName", "string"),
            ],
            "device.listPresets" => &[("refresh", "boolean"), ("setlistKey", "nullable-string")],
            "device.listPresetFolders" => &[("refresh", "boolean")],
            "device.navigateBank" => &[
                ("direction", "integer"),
                ("expectedPresetName", "string"),
                ("expectedPosition", "integer"),
            ],
            "device.recallPreset" => &[
                ("setlistKey", "string"),
                ("position", "integer"),
                ("expectedPresetName", "string"),
                ("expectedPosition", "integer"),
                ("expectedSetlistKey", "string"),
            ],
            "device.reloadPreset" => &[
                ("expectedPresetName", "string"),
                ("expectedPosition", "integer"),
            ],
            "device.blockDetails" => &[
                ("row", "integer"),
                ("column", "integer"),
                ("expectedPresetName", "string"),
            ],
            "device.laneControlDetails" => &[
                ("row", "integer"),
                ("control", "string"),
                ("expectedPresetName", "string"),
            ],
            "device.previewParameter" => &[
                ("row", "integer"),
                ("column", "integer"),
                ("parameterIndex", "integer"),
                ("value", "number"),
                ("expectedValue", "number"),
                ("expectedScene", "integer"),
                ("expectedPresetName", "string"),
            ],
            "device.previewLaneControlParameter" => &[
                ("row", "integer"),
                ("control", "string"),
                ("parameterIndex", "integer"),
                ("value", "number"),
                ("expectedValue", "number"),
                ("expectedPresetName", "string"),
            ],
            "device.setParameter" => &[
                ("row", "integer"),
                ("column", "integer"),
                ("parameterIndex", "integer"),
                ("value", "number"),
                ("expectedValue", "number"),
                ("expectedScene", "integer"),
                ("expectedPresetName", "string"),
            ],
            "device.setLaneControlParameter" => &[
                ("row", "integer"),
                ("control", "string"),
                ("parameterIndex", "integer"),
                ("value", "number"),
                ("expectedValue", "number"),
                ("expectedPresetName", "string"),
            ],
            "device.setLaneControlSceneMode" => &[
                ("row", "integer"),
                ("control", "string"),
                ("parameterIndex", "integer"),
                ("enabled", "boolean"),
                ("expectedPresetName", "string"),
            ],
            "device.setParameterSceneMode" => &[
                ("row", "integer"),
                ("column", "integer"),
                ("parameterIndex", "integer"),
                ("enabled", "boolean"),
                ("expectedPresetName", "string"),
            ],
            "device.setParameterExpression" => &[
                ("row", "integer"),
                ("column", "integer"),
                ("parameterIndex", "integer"),
                ("pedal", "integer"),
                ("minimum", "number"),
                ("maximum", "number"),
                ("expectedPresetName", "string"),
            ],
            "device.setTempo" => &[
                ("bpm", "integer"),
                ("expectedTempo", "integer"),
                ("expectedPresetName", "string"),
            ],
            "device.setMasterVolume" => &[("value", "integer"), ("expectedValue", "integer")],
            "device.masterVolume" => &[],
            "device.pressFootswitch" => &[
                ("index", "integer"),
                ("expectedMode", "string"),
                ("expectedPresetName", "string"),
            ],
            "device.tapTempo" => &[("expectedMode", "string"), ("expectedPresetName", "string")],
            "device.selectModeSlot" => &[("slot", "integer"), ("expectedPresetName", "string")],
            "device.listPresetSlots" => &[],
            "device.savePresetAs" => &[
                ("setlistKey", "string"),
                ("position", "integer"),
                ("name", "string"),
                ("expectedPresetName", "string"),
                ("expectedPosition", "integer"),
                ("confirmOverwrite", "boolean"),
            ],
            "device.copyPreset" => &[
                ("sourceSetlistKey", "string"),
                ("sourcePosition", "integer"),
                ("sourceName", "string"),
                ("destinationSetlistKey", "string"),
                ("destinationPosition", "integer"),
                ("expectedPresetName", "string"),
                ("expectedPosition", "integer"),
                ("confirmOverwrite", "boolean"),
            ],
            "device.renameCurrentPreset" => &[
                ("name", "string"),
                ("expectedPresetName", "string"),
                ("expectedPosition", "integer"),
                ("confirmRename", "boolean"),
            ],
            "device.createBackup" => &[("name", "string")],
            "device.showTuner" => &[("shown", "boolean")],
            "device.showGigView" => &[("shown", "boolean")],
            _ => &[],
        };
        for (key, kind) in kinds {
            let Some(value) = object.get(*key) else {
                continue;
            };
            let (nullable, base) = kind
                .strip_prefix("nullable-")
                .map_or((false, *kind), |base| (true, base));
            if nullable && value.is_null() {
                continue;
            }
            let valid = match base {
                "boolean" => value.is_boolean(),
                "integer" => value.is_i64() || value.is_u64(),
                "number" => value.as_f64().is_some_and(f64::is_finite),
                "string" => value.is_string(),
                "array" => value.is_array(),
                _ => false,
            };
            if !valid {
                return Err(format!("{method}.{key} must be {kind}"));
            }
        }
    }
    Ok(())
}

#[allow(dead_code)]
pub mod rpc {
    pub const RUNTIME_STATUS: &str = "system.status";
    pub const RECONNECT: &str = "device.reconnect";
    pub const RESET_SESSION: &str = "device.resetSession";
    pub const DISCONNECT: &str = "device.disconnect";
    pub const CURRENT_SNAPSHOT: &str = "device.snapshot";
    pub const CURRENT_STATE_EVENTS: &str = "device.stateEvents";
    pub const CURRENT_TEMPO_CLOCK: &str = "device.tempoClock";
    pub const LIST_MODELS: &str = "device.listModels";
    pub const IDENTITY: &str = "device.identity";
    pub const SET_DEVICE_NAME: &str = "device.setDeviceName";
    pub const UNDO: &str = "device.undo";
    pub const REDO: &str = "device.redo";
    pub const INHIBITED_MODULES: &str = "device.inhibitedModules";
    pub const TUNER_SETTINGS: &str = "device.tunerSettings";
    pub const SET_TUNER_INPUT: &str = "device.setTunerInput";
    pub const SET_TUNER_MUTE: &str = "device.setTunerMute";
    pub const RESTORE_TUNER_AUDIO: &str = "device.restoreTunerAudio";
    pub const SET_TUNER_REFERENCE: &str = "device.setTunerReference";
    pub const SET_TUNER_METER: &str = "device.setTunerMeter";
    pub const GENERAL_SETTINGS: &str = "device.generalSettings";
    pub const IO_SETTINGS: &str = "device.ioSettings";
    pub const SET_INPUT_PORT: &str = "device.setInputPort";
    pub const SET_OUTPUT_PORT: &str = "device.setOutputPort";
    pub const SET_USB_PORT: &str = "device.setUsbPort";
    pub const SET_MIDI_THRU: &str = "device.setMidiThru";
    pub const SET_OUTPUT_PAIRING: &str = "device.setOutputPairing";
    pub const GLOBAL_EQ: &str = "device.globalEq";
    pub const SET_GLOBAL_EQ_BYPASSED: &str = "device.setGlobalEqBypassed";
    pub const SET_GLOBAL_EQ_BAND: &str = "device.setGlobalEqBand";
    pub const SET_GLOBAL_EQ_OUTPUT: &str = "device.setGlobalEqOutput";
    pub const MODE_CYCLE: &str = "device.modeCycle";
    pub const SET_MODE_CYCLE: &str = "device.setModeCycle";
    pub const GLOBAL_TEMPO_SETTINGS: &str = "device.globalTempoSettings";
    pub const SET_TEMPO_METRONOME: &str = "device.setTempoMetronome";
    pub const SET_TEMPO_MODE: &str = "device.setTempoMode";
    pub const SET_GLOBAL_TEMPO: &str = "device.setGlobalTempo";
    pub const LOOPER_STATUS: &str = "device.looperStatus";
    pub const CONTROL_LOOPER: &str = "device.controlLooper";
    pub const RECENTS: &str = "device.recents";
    pub const FAVORITES: &str = "device.favorites";
    pub const SET_FAVORITE: &str = "device.setFavorite";
    pub const PINNED_MODELS: &str = "device.pinnedModels";
    pub const SET_MODEL_PINNED: &str = "device.setModelPinned";
    pub const CAPTURES: &str = "device.captures";
    pub const LOAD_CAPTURE: &str = "device.loadCapture";
    pub const IRS: &str = "device.irs";
    pub const LOAD_IR: &str = "device.loadIr";
    pub const CREATE_SETLIST: &str = "device.createSetlist";
    pub const DELETE_SETLIST: &str = "device.deleteSetlist";
    pub const DUPLICATE_SETLIST: &str = "device.duplicateSetlist";
    pub const DELETE_PRESET: &str = "device.deletePreset";
    pub const MOVE_PRESET: &str = "device.movePreset";
    pub const SET_GENERAL_INTEGER: &str = "device.setGeneralInteger";
    pub const SET_GENERAL_TOGGLE: &str = "device.setGeneralToggle";
    pub const SET_SCENE_BYPASS_BEHAVIOR: &str = "device.setSceneBypassBehavior";
    pub const SET_MASTER_VOLUME_ASSIGNMENT: &str = "device.setMasterVolumeAssignment";
    pub const SET_GLOBAL_BYPASS: &str = "device.setGlobalBypass";
    pub const PRESET_SCREENSHOT: &str = "device.presetScreenshot";
    pub const CAPTURE_SCREEN: &str = "device.captureScreen";
    pub const GRAPHICS_TREE: &str = "device.graphicsTree";
    pub const TAP_SCREEN: &str = "device.tapScreen";
    pub const SWIPE_SCREEN: &str = "device.swipeScreen";
    pub const SELECT_SCENE: &str = "device.selectScene";
    pub const COPY_SCENE: &str = "device.copyScene";
    pub const SET_SCENE_LABEL: &str = "device.setSceneLabel";
    pub const SET_SCENE_COLOR: &str = "device.setSceneColor";
    pub const TOGGLE_BYPASS: &str = "device.toggleBypass";
    pub const MOVE_BLOCK: &str = "device.moveBlock";
    pub const ADD_BLOCK: &str = "device.addBlock";
    pub const REMOVE_BLOCK: &str = "device.removeBlock";
    pub const SET_BLOCK_FOOTSWITCH: &str = "device.setBlockFootswitch";
    pub const SET_STOMP_MOMENTARY: &str = "device.setStompMomentary";
    pub const SET_STOMP_LABEL: &str = "device.setStompLabel";
    pub const SET_MIDI_OUT: &str = "device.setMidiOut";
    pub const SET_PRESET_LOAD_MIDI_OUT: &str = "device.setPresetLoadMidiOut";
    pub const SET_EXPRESSION_BYPASS: &str = "device.setExpressionBypass";
    pub const SET_CHAIN_INPUT: &str = "device.setChainInput";
    pub const SET_CHAIN_OUTPUT: &str = "device.setChainOutput";
    pub const SET_CHAIN_SPLIT: &str = "device.setChainSplit";
    pub const SET_SPLIT_MUTE: &str = "device.setSplitMute";
    pub const LIST_PRESETS: &str = "device.listPresets";
    pub const LIST_PRESET_FOLDERS: &str = "device.listPresetFolders";
    pub const NAVIGATE_BANK: &str = "device.navigateBank";
    pub const RECALL_PRESET: &str = "device.recallPreset";
    pub const RELOAD_PRESET: &str = "device.reloadPreset";
    pub const BLOCK_DETAILS: &str = "device.blockDetails";
    pub const LANE_CONTROL_DETAILS: &str = "device.laneControlDetails";
    pub const PREVIEW_PARAMETER: &str = "device.previewParameter";
    pub const PREVIEW_LANE_CONTROL_PARAMETER: &str = "device.previewLaneControlParameter";
    pub const SET_PARAMETER: &str = "device.setParameter";
    pub const SET_LANE_CONTROL_PARAMETER: &str = "device.setLaneControlParameter";
    pub const SET_LANE_CONTROL_SCENE_MODE: &str = "device.setLaneControlSceneMode";
    pub const SET_PARAMETER_SCENE_MODE: &str = "device.setParameterSceneMode";
    pub const SET_PARAMETER_EXPRESSION: &str = "device.setParameterExpression";
    pub const SET_TEMPO: &str = "device.setTempo";
    pub const SET_MASTER_VOLUME: &str = "device.setMasterVolume";
    pub const CURRENT_MASTER_VOLUME: &str = "device.masterVolume";
    pub const PRESS_FOOTSWITCH: &str = "device.pressFootswitch";
    pub const TAP_TEMPO: &str = "device.tapTempo";
    pub const SELECT_MODE_SLOT: &str = "device.selectModeSlot";
    pub const LIST_PRESET_SLOTS: &str = "device.listPresetSlots";
    pub const SAVE_PRESET_AS: &str = "device.savePresetAs";
    pub const COPY_PRESET: &str = "device.copyPreset";
    pub const RENAME_CURRENT_PRESET: &str = "device.renameCurrentPreset";
    pub const CREATE_DEVICE_BACKUP: &str = "device.createBackup";
    pub const SHOW_TUNER: &str = "device.showTuner";
    pub const SHOW_GIG_VIEW: &str = "device.showGigView";
}
