"""Generate canonical pixel-vector paths from authoritative CorOS icon crops."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

from PIL import Image


REFERENCE_ROOTS = {
    "official": Path("references/qc-ui-official-manual/coros-4.1.0"),
    "corpus": Path("references/qc-ui-corpus/coros-4.1.0"),
    "app-golden": Path("references/qc-ui-app-golden/v1"),
}


def color(value: str) -> tuple[int, int, int]:
    return tuple(int(value[index:index + 2], 16) for index in (1, 3, 5))


def raster_path(image: Image.Image, expected: tuple[int, int, int], tolerance: float) -> str:
    pixels = image.load()
    parts: list[str] = []
    for y in range(image.height):
        x = 0
        while x < image.width:
            while x < image.width and math.dist(pixels[x, y], expected) > tolerance:
                x += 1
            if x == image.width:
                break
            start = x
            while x < image.width and math.dist(pixels[x, y], expected) <= tolerance:
                x += 1
            width = x - start
            parts.append(f"M{start} {y}h{width}v1h-{width}Z")
    return "".join(parts)


def render(manifest: dict) -> str:
    entries = []
    for measurement in manifest["screenMeasurements"]:
        if measurement["icon"] not in manifest["canonicalRasterIcons"]:
            continue
        source_set = measurement.get("sourceSet", "official")
        root = REFERENCE_ROOTS[source_set]
        x, y, width, height = measurement["crop"]
        crop = Image.open(root / f'{measurement["screen"]}.png').convert("RGB").crop((x, y, x + width, y + height))
        expected_colors = [color(value) for value in measurement["expectedColors"]]
        background = color(measurement["referenceBackground"])
        tolerance = max(2.0, min(20.0, min(math.dist(value, background) for value in expected_colors) / 2.0))
        paths = {value: raster_path(crop, color(value), tolerance) for value in measurement["expectedColors"]}
        entries.append((measurement["icon"], width, height, paths))
    lines = [
        "// Generated by tools/generate_qc_icon_rasters.py. Do not edit.",
        "export const QC_REFERENCE_ICON_RASTERS = {",
    ]
    for icon, width, height, paths in entries:
        path_text = ", ".join(f'{json.dumps(key)}: {json.dumps(value)}' for key, value in paths.items())
        lines.append(f'  {json.dumps(icon)}: {{ width: {width}, height: {height}, paths: {{ {path_text} }} }},')
    lines.extend(["} as const;", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, default=Path("references/qc-ui-iconography/coros-4.1.0/manifest.json"))
    parser.add_argument("--output", type=Path, default=Path("packages/typescript/qc-theme/src/reference-icon-rasters.ts"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render(json.loads(args.manifest.read_text(encoding="utf-8")))
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != generated:
            print(f"stale generated icon registry: {args.output}")
            return 1
        return 0
    args.output.write_text(generated, encoding="utf-8")
    print(f"Generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
