"""Render the .proto files from the schema shipped inside Cortex Control.

The protos under packages/rust/qc-protocol/proto used to be maintained by hand.
They had drifted from the schema the device actually speaks: 417 fields had lost
their explicit presence, GlobalEQMessage field 5 was declared a bool named
`has_user_defaults` where the binary says it is a `ModelPresetID` message named
`model_preset_to_load`, and two dozen fields added by newer firmware were simply
absent. A hand-written copy of someone else's schema drifts by default.

So the schema is no longer transcribed, it is generated: this renders the
serialized FileDescriptorProto that `extract-cortex-protocol.py` lifts out of
the binary back into .proto text, and `verify_cortex_protocol_fidelity.py`
proves the round trip is exact.

Usage:
  python tools/generate_cortex_protos.py [--check]

--check renders and compares without writing, for CI.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from google.protobuf import descriptor_pb2

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DESCRIPTORS = REPOSITORY_ROOT / "artifacts/cortex-protocol"
PROTO_DIRECTORY = REPOSITORY_ROOT / "packages/rust/qc-protocol/proto"
FILES = ("ProductionAutomation", "Preset")

SCALARS = {
    1: "double", 2: "float", 3: "int64", 4: "uint64", 5: "int32",
    6: "fixed64", 7: "fixed32", 8: "bool", 9: "string",
    12: "bytes", 13: "uint32", 15: "sfixed32", 16: "sfixed64",
    17: "sint32", 18: "sint64",
}

HEADER = """// Generated by tools/generate_cortex_protos.py from the descriptors that
// Cortex Control carries in its own binary. Do not edit by hand: run
//   python tools/generate_cortex_protos.py
// after refreshing artifacts/cortex-protocol with extract-cortex-protocol.py.
//
// This is the schema the Quad Cortex speaks. It is reproduced here so an
// independent controller can talk to a device its owner already has;
// verify_cortex_protocol_fidelity.py proves it matches the shipped copy field
// for field.

"""


def type_name(field: descriptor_pb2.FieldDescriptorProto) -> str:
    if field.type in (11, 14):          # message, enum
        return field.type_name
    return SCALARS[field.type]


def map_entries(message: descriptor_pb2.DescriptorProto) -> dict[str, str]:
    """Nested MapEntry messages are how a `map<k, v>` field is represented."""
    entries = {}
    for nested in message.nested_type:
        if not nested.options.map_entry:
            continue
        key = next(field for field in nested.field if field.number == 1)
        value = next(field for field in nested.field if field.number == 2)
        entries[nested.name] = f"map<{type_name(key)}, {type_name(value)}>"
    return entries


def render_message(message: descriptor_pb2.DescriptorProto, indent: str) -> list[str]:
    lines = [f"{indent}message {message.name} {{"]
    inner = indent + "  "
    entries = map_entries(message)

    for nested in message.nested_type:
        if nested.options.map_entry:
            continue
        lines += render_message(nested, inner)
        lines.append("")

    for enum in message.enum_type:
        lines += render_enum(enum, inner)
        lines.append("")

    # A `optional` field in proto3 is carried as a one-field synthetic oneof, so
    # those are unwrapped back into the keyword rather than emitted as oneofs.
    synthetic = {
        field.oneof_index for field in message.field
        if field.HasField("oneof_index") and field.proto3_optional
    }
    emitted_oneofs: set[int] = set()

    for field in message.field:
        if field.HasField("oneof_index") and field.oneof_index not in synthetic:
            index = field.oneof_index
            if index in emitted_oneofs:
                continue
            emitted_oneofs.add(index)
            lines.append(f"{inner}oneof {message.oneof_decl[index].name} {{")
            for member in message.field:
                if member.HasField("oneof_index") and member.oneof_index == index:
                    kind = entries.get(member.type_name.rsplit(".", 1)[-1]) or type_name(member)
                    lines.append(f"{inner}  {kind} {member.name} = {member.number};")
            lines.append(f"{inner}}}")
            continue
        if field.HasField("oneof_index") and field.oneof_index in synthetic:
            prefix = "optional "
        elif field.label == 3:
            prefix = "repeated "
        else:
            prefix = ""
        kind = entries.get(field.type_name.rsplit(".", 1)[-1]) if field.type_name else None
        if kind:                         # a map field is never labelled repeated
            prefix = ""
        else:
            kind = type_name(field)
        lines.append(f"{inner}{prefix}{kind} {field.name} = {field.number};")

    lines.append(f"{indent}}}")
    return lines


def render_enum(enum: descriptor_pb2.EnumDescriptorProto, indent: str) -> list[str]:
    lines = [f"{indent}enum {enum.name} {{"]
    for value in enum.value:
        lines.append(f"{indent}  {value.name} = {value.number};")
    lines.append(f"{indent}}}")
    return lines


def render(proto: descriptor_pb2.FileDescriptorProto) -> str:
    lines = [HEADER.rstrip("\n"), "", 'syntax = "proto3";', ""]
    if proto.package:
        lines += [f"package {proto.package};", ""]
    for dependency in proto.dependency:
        lines.append(f'import "{dependency}";')
    if proto.dependency:
        lines.append("")
    for message in proto.message_type:
        lines += render_message(message, "")
        lines.append("")
    for enum in proto.enum_type:
        lines += render_enum(enum, "")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the checked-in protos differ from the render")
    arguments = parser.parse_args()

    stale = []
    for stem in FILES:
        descriptor = DESCRIPTORS / f"{stem}.desc"
        if not descriptor.is_file():
            print(f"missing {descriptor}; run tools/extract-cortex-protocol.py",
                  file=sys.stderr)
            return 2
        proto = descriptor_pb2.FileDescriptorProto()
        proto.ParseFromString(descriptor.read_bytes())
        rendered = render(proto)
        target = PROTO_DIRECTORY / f"{stem}.proto"
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current == rendered:
            print(f"{stem}.proto: up to date")
            continue
        if arguments.check:
            stale.append(stem)
            print(f"FAIL {stem}.proto is not what the descriptor renders")
            continue
        target.write_text(rendered, encoding="utf-8")
        print(f"{stem}.proto: written ({len(rendered.splitlines())} lines)")

    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
