"""Generate a Rust registry covering every message type the device declares.

Verifying that our .proto files match Cortex Control's proves we describe the
protocol correctly. It does not make the protocol *implemented*: until now the
crate could only encode or decode the types someone had hand-wired, so 26 of the
72 types had no code path at all.

This renders `packages/rust/qc-protocol/src/message_registry.rs` from
`references/cortex-protocol/message-types.json`, which is itself lifted out of
the binary. Every declared type gets a variant, a decoder and an encoder, so the
transport can round-trip anything the device sends and anything Cortex Control
would send. Which of them the *application* chooses to expose is a separate
decision, recorded in references/cortex-protocol/message-type-plan.json.

Generated rather than written so it cannot drift from the enum: a type added by
a future Cortex Control appears here the moment the descriptors are refreshed.

Usage:
  python tools/generate_cortex_message_registry.py [--check]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
TYPES = REPOSITORY_ROOT / "references/cortex-protocol/message-types.json"
TARGET = REPOSITORY_ROOT / "packages/rust/qc-protocol/src/message_registry.rs"

SENTINELS = {"Undefined", "NumberOfMessageTypes"}

# prost renames a proto message with `heck`'s UpperCamelCase, so an acronym run
# such as GlobalEQMessage becomes GlobalEqMessage. Splitting the same way keeps
# the generated paths compiling without a hand-maintained exception list.
BOUNDARY = re.compile(r"[A-Z]+(?![a-z])|[A-Z][a-z0-9]*|[a-z0-9]+")


def upper_camel_case(name: str) -> str:
    return "".join(word[:1].upper() + word[1:].lower() for word in BOUNDARY.findall(name))


def render(types: dict[int, str]) -> str:
    entries = [(number, name) for number, name in sorted(types.items())
               if name not in SENTINELS]

    lines = [
        "// Generated by tools/generate_cortex_message_registry.py from the",
        "// CortexMessageType table inside Cortex Control. Do not edit by hand.",
        "//",
        "// Every type the device declares is decodable and encodable here, so the",
        "// transport can round-trip anything on the link. Whether the application",
        "// exposes a type is a separate decision; see",
        "// references/cortex-protocol/message-type-plan.json.",
        "",
        "use crate::proto::cortex_protobuf_v2 as pa;",
        "use prost::Message;",
        "",
        "/// Every `CortexMessageType` value the shipped binary declares, excluding",
        "/// the `Undefined` and `NumberOfMessageTypes` sentinels.",
        f"pub const MESSAGE_TYPES: [(u16, &str); {len(entries)}] = [",
    ]
    for number, name in entries:
        lines.append(f'    ({number}, "{name}"),')
    lines.append("];")
    lines.append("")
    lines.append("/// One decoded message of any declared type.")
    lines.append("#[derive(Debug, Clone, PartialEq)]")
    lines.append("pub enum DecodedMessage {")
    for _, name in entries:
        # Boxed uniformly: the messages differ hugely in size - a Grid carries a
        # whole BinaryPreset - and an unboxed enum would be as large as its
        # biggest variant everywhere it is passed.
        lines.append(f"    {upper_camel_case(name)}(Box<pa::{upper_camel_case(name)}Message>),")
    lines.append("}")
    lines.append("")
    lines.append("impl DecodedMessage {")
    lines.append("    /// The wire type number this message is sent under.")
    lines.append("    pub fn message_type(&self) -> u16 {")
    lines.append("        match self {")
    for number, name in entries:
        lines.append(f"            Self::{upper_camel_case(name)}(_) => {number},")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    /// The protobuf body, ready for the framing layer.")
    lines.append("    pub fn encode(&self) -> Vec<u8> {")
    lines.append("        match self {")
    for _, name in entries:
        lines.append(f"            Self::{upper_camel_case(name)}(message) => message.encode_to_vec(),")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("/// The declared name of a message type, for logging and diagnostics.")
    lines.append("pub fn message_name(message_type: u16) -> Option<&'static str> {")
    lines.append("    MESSAGE_TYPES")
    lines.append("        .iter()")
    lines.append("        .find(|(number, _)| *number == message_type)")
    lines.append("        .map(|(_, name)| *name)")
    lines.append("}")
    lines.append("")
    lines.append("/// Decode any declared type. `None` for a type the binary does not")
    lines.append("/// declare, which is how an unknown push is told apart from a corrupt one.")
    lines.append("pub fn decode_any(")
    lines.append("    message_type: u16,")
    lines.append("    payload: &[u8],")
    lines.append(") -> Option<Result<DecodedMessage, prost::DecodeError>> {")
    lines.append("    let decoded = match message_type {")
    for number, name in entries:
        variant = upper_camel_case(name)
        lines.append(f"        {number} => pa::{variant}Message::decode(payload)"
                     f".map(|message| DecodedMessage::{variant}(Box::new(message))),")
    lines.append("        _ => return None,")
    lines.append("    };")
    lines.append("    Some(decoded)")
    lines.append("}")
    lines.append("")
    lines.append("#[cfg(test)]")
    lines.append("mod tests {")
    lines.append("    use super::*;")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn every_declared_type_round_trips() {")
    lines.append("        for (number, name) in MESSAGE_TYPES {")
    lines.append("            let decoded = decode_any(number, &[])")
    lines.append("                .unwrap_or_else(|| panic!(\"{number} {name} is not decodable\"))")
    lines.append("                .unwrap_or_else(|error| panic!(\"{number} {name}: {error}\"));")
    lines.append("            assert_eq!(decoded.message_type(), number, \"{name}\");")
    lines.append("            assert!(decoded.encode().is_empty(), \"{name} encodes an empty body\");")
    lines.append("            assert_eq!(message_name(number), Some(name));")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn an_undeclared_type_is_reported_rather_than_guessed() {")
    lines.append("        assert!(decode_any(0, &[]).is_none());")
    lines.append("        assert!(decode_any(73, &[]).is_none());")
    lines.append("        assert!(message_name(73).is_none());")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    types = {int(number): name
             for number, name in json.loads(TYPES.read_text(encoding="utf-8")).items()}
    rendered = render(types)
    current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else None

    if current == rendered:
        print(f"{TARGET.name}: up to date "
              f"({len([n for n in types.values() if n not in SENTINELS])} types)")
        return 0
    if arguments.check:
        print(f"FAIL {TARGET.name} is not what the message-type table renders",
              file=sys.stderr)
        return 1
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"{TARGET.name}: written ({len(rendered.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
