// Generated by scripts/generate-qc-actions.mjs. Do not edit by hand.
pub static ACTIONS: &[ActionSpec] = &[
    ActionSpec {
        name: "reconnect_device",
        rpc: "device.reconnect",
        classification: Classification::RiskyWrite,
        description: "Reconnect the native Quad Cortex transport after explicit confirmation.",
        properties: &[p!("confirm_risky_operation", Kind::Boolean)],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "reset_device_session",
        rpc: "device.resetSession",
        classification: Classification::RiskyWrite,
        description: "Reset and re-synchronize the native Quad Cortex communication session after explicit confirmation.",
        properties: &[p!("confirm_risky_operation", Kind::Boolean)],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "disconnect_device",
        rpc: "device.disconnect",
        classification: Classification::RiskyWrite,
        description: "Close the native Quad Cortex transport after explicit confirmation.",
        properties: &[p!("confirm_risky_operation", Kind::Boolean)],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_current_preset",
        rpc: "device.snapshot",
        classification: Classification::Read,
        description: "Read the authoritative current preset, scene, tempo and Grid state.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_state_events",
        rpc: "device.stateEvents",
        classification: Classification::Read,
        description: "Read native state frames after a sequence cursor.",
        properties: &[
            p!("after_sequence", Kind::Integer { min: 0, max: None }),
            p!("limit", Kind::Integer { min: 0, max: None }),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("after_sequence", "afterSequence"), ("limit", "limit")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_tempo_clock",
        rpc: "device.tempoClock",
        classification: Classification::Read,
        description: "Read the most recent native metronome beat, bar and tick state.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_block_details",
        rpc: "device.blockDetails",
        classification: Classification::Read,
        description: "Read live parameters for one occupied Grid block, splitter, or mixer.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!(
                "column",
                Kind::Integer {
                    min: 0,
                    max: Some(9)
                }
            ),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("column", "column"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_lane_control_details",
        rpc: "device.laneControlDetails",
        classification: Classification::Read,
        description: "Read the Input Gate or Lane Output parameters attached to a signal row.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!("control", Kind::StringEnum(&["inputGate", "laneOutput"])),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("control", "control"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "list_models",
        rpc: "device.listModels",
        classification: Classification::Read,
        description: "Find installed block models and their numeric IDs.",
        properties: &[p!("query", Kind::NullableString)],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "list_presets",
        rpc: "device.listPresets",
        classification: Classification::Read,
        description: "List presets in a setlist, optionally refreshing the device index.",
        properties: &[
            p!("refresh", Kind::Boolean),
            p!("setlist_key", Kind::NullableString),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("refresh", "refresh"), ("setlist_key", "setlistKey")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "list_preset_folders",
        rpc: "device.listPresetFolders",
        classification: Classification::Read,
        description: "List preset folders and setlists, optionally refreshing the device index.",
        properties: &[p!("refresh", Kind::Boolean)],
        distinct_arguments: &[],
        gateway_arguments: &[("refresh", "refresh")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "list_preset_slots",
        rpc: "device.listPresetSlots",
        classification: Classification::Read,
        description: "List preset destinations and their occupancy before a persistent write.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_master_volume",
        rpc: "device.masterVolume",
        classification: Classification::Read,
        description: "Read the authoritative master output volume.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_device_identity",
        rpc: "device.identity",
        classification: Classification::Read,
        description: "Read the connected Quad Cortex serial number, firmware version, type and custom name.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_inhibited_modules",
        rpc: "device.inhibitedModules",
        classification: Classification::Read,
        description: "Read the authoritative Global Gate and Global EQ inhibition state.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_tuner_settings",
        rpc: "device.tunerSettings",
        classification: Classification::Read,
        description: "Read the tuner input, mute preference, and reference pitch without changing or engaging the tuner.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_tuner_input",
        rpc: "device.setTunerInput",
        classification: Classification::RiskyWrite,
        description: "Choose the tuner input. This invisibly engages the tuner and can silence the rig if its mute preference is enabled.",
        properties: &[
            p!(
                "input_port_id",
                Kind::Integer {
                    min: 1,
                    max: Some(9)
                }
            ),
            p!("confirm_tuner_activation", Kind::Boolean),
            p!("confirm_risky_operation", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("input_port_id", "inputPortId"),
            ("confirm_tuner_activation", "confirmTunerActivation"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_tuner_mute",
        rpc: "device.setTunerMute",
        classification: Classification::RiskyWrite,
        description: "Change mute-while-tuning. This invisibly engages the tuner; enabling mute immediately silences all outputs.",
        properties: &[
            p!("muted", Kind::Boolean),
            p!("confirm_tuner_activation", Kind::Boolean),
            p!("confirm_risky_operation", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("muted", "muted"),
            ("confirm_tuner_activation", "confirmTunerActivation"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "restore_tuner_audio",
        rpc: "device.restoreTunerAudio",
        classification: Classification::RiskyWrite,
        description: "Restore audio after a host tuner write by clearing the persistent mute-while-tuning preference.",
        properties: &[
            p!("confirm_preference_reset", Kind::Boolean),
            p!("confirm_risky_operation", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("confirm_preference_reset", "confirmPreferenceReset")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_tuner_reference",
        rpc: "device.setTunerReference",
        classification: Classification::RiskyWrite,
        description: "Set tuner reference as an Hz offset from 440. This invisibly engages the tuner.",
        properties: &[
            p!(
                "reference_offset_hz",
                Kind::Number {
                    min: -f64::MAX,
                    max: Some(f64::MAX)
                }
            ),
            p!("confirm_tuner_activation", Kind::Boolean),
            p!("confirm_risky_operation", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("reference_offset_hz", "referenceOffsetHz"),
            ("confirm_tuner_activation", "confirmTunerActivation"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_preset_screenshot",
        rpc: "device.presetScreenshot",
        classification: Classification::Read,
        description: "Read the PNG thumbnail stored for a preset.",
        properties: &[
            p!("folder_name", Kind::String),
            p!("position", Kind::Integer { min: 0, max: None }),
            p!("is_factory", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("folder_name", "folderName"),
            ("position", "position"),
            ("is_factory", "isFactory"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "capture_screen",
        rpc: "device.captureScreen",
        classification: Classification::Read,
        description: "Capture the current Quad Cortex touchscreen as a PNG image.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "preview_parameter",
        rpc: "device.previewParameter",
        classification: Classification::LiveWrite,
        description: "Preview a block, splitter, or mixer parameter value without waiting for device verification.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!(
                "column",
                Kind::Integer {
                    min: 0,
                    max: Some(9)
                }
            ),
            p!("parameter_index", Kind::Integer { min: 0, max: None }),
            p!(
                "value",
                Kind::Number {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "expected_value",
                Kind::Number {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "expected_scene",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("column", "column"),
            ("parameter_index", "parameterIndex"),
            ("value", "value"),
            ("expected_value", "expectedValue"),
            ("expected_scene", "expectedScene"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "preview_lane_control_parameter",
        rpc: "device.previewLaneControlParameter",
        classification: Classification::LiveWrite,
        description: "Preview an Input Gate or Lane Output parameter without waiting for device verification.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!("control", Kind::StringEnum(&["inputGate", "laneOutput"])),
            p!("parameter_index", Kind::Integer { min: 0, max: None }),
            p!(
                "value",
                Kind::Number {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "expected_value",
                Kind::Number {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("control", "control"),
            ("parameter_index", "parameterIndex"),
            ("value", "value"),
            ("expected_value", "expectedValue"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "create_device_backup",
        rpc: "device.createBackup",
        classification: Classification::PersistentWrite,
        description: "Create a complete local device backup after explicit confirmation.",
        properties: &[
            p!("name", Kind::VisibleString { max_chars: 64 }),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("name", "name")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_device_name",
        rpc: "device.setDeviceName",
        classification: Classification::PersistentWrite,
        description: "Change the Quad Cortex custom name after explicit confirmation.",
        properties: &[
            p!("name", Kind::VisibleString { max_chars: 64 }),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("name", "name")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "undo_device",
        rpc: "device.undo",
        classification: Classification::RiskyWrite,
        description: "Undo the most recent device edit after explicit confirmation.",
        properties: &[p!("confirm_risky_operation", Kind::Boolean)],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "redo_device",
        rpc: "device.redo",
        classification: Classification::RiskyWrite,
        description: "Redo the most recently undone device edit after explicit confirmation.",
        properties: &[p!("confirm_risky_operation", Kind::Boolean)],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "tap_screen",
        rpc: "device.tapScreen",
        classification: Classification::RiskyWrite,
        description: "Tap an exact touchscreen pixel after reviewing a fresh screen capture and explicitly confirming the action.",
        properties: &[
            p!(
                "x",
                Kind::Integer {
                    min: 0,
                    max: Some(799)
                }
            ),
            p!(
                "y",
                Kind::Integer {
                    min: 0,
                    max: Some(479)
                }
            ),
            p!("confirm_risky_operation", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("x", "x"), ("y", "y")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "select_scene",
        rpc: "device.selectScene",
        classification: Classification::LiveWrite,
        description: "Immediately select a performance scene, numbered 0 through 7.",
        properties: &[
            p!(
                "scene",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("scene", "scene"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "copy_scene",
        rpc: "device.copyScene",
        classification: Classification::LiveWrite,
        description: "Copy or swap two scenes in the current preset and verify the resulting scene state.",
        properties: &[
            p!(
                "from_scene",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!(
                "to_scene",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!("swap", Kind::Boolean),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[("from_scene", "to_scene")],
        gateway_arguments: &[
            ("from_scene", "fromScene"),
            ("to_scene", "toScene"),
            ("swap", "swap"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_scene_label",
        rpc: "device.setSceneLabel",
        classification: Classification::LiveWrite,
        description: "Set or clear the label of one scene in the current preset.",
        properties: &[
            p!(
                "scene",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!("label", Kind::NullableVisibleString { max_chars: 32 }),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("scene", "scene"),
            ("label", "label"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_scene_color",
        rpc: "device.setSceneColor",
        classification: Classification::LiveWrite,
        description: "Set the display color of one scene in the current preset.",
        properties: &[
            p!(
                "scene",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!(
                "color",
                Kind::Integer {
                    min: 0,
                    max: Some(4294967295)
                }
            ),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("scene", "scene"),
            ("color", "color"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "press_footswitch",
        rpc: "device.pressFootswitch",
        classification: Classification::LiveWrite,
        description: "Press a physical Quad Cortex footswitch by its stable hardware index.",
        properties: &[
            p!(
                "index",
                Kind::Integer {
                    min: 0,
                    max: Some(10)
                }
            ),
            p!("expected_mode", Kind::String),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("index", "index"),
            ("expected_mode", "expectedMode"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "tap_tempo",
        rpc: "device.tapTempo",
        classification: Classification::LiveWrite,
        description: "Tap the dedicated Quad Cortex tempo control through its official MIDI command.",
        properties: &[
            p!("expected_mode", Kind::String),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("expected_mode", "expectedMode"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "navigate_bank",
        rpc: "device.navigateBank",
        classification: Classification::LiveWrite,
        description: "Immediately navigate one performance bank down (-1) or up (1).",
        properties: &[
            p!("direction", Kind::IntegerEnum(&[-1, 1])),
            p!("expected_preset_name", Kind::String),
            p!("expected_position", Kind::Integer { min: 0, max: None }),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("direction", "direction"),
            ("expected_preset_name", "expectedPresetName"),
            ("expected_position", "expectedPosition"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "show_tuner",
        rpc: "device.showTuner",
        classification: Classification::LiveWrite,
        description: "Show or hide the tuner.",
        properties: &[p!("shown", Kind::Boolean)],
        distinct_arguments: &[],
        gateway_arguments: &[("shown", "shown")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "show_gig_view",
        rpc: "device.showGigView",
        classification: Classification::LiveWrite,
        description: "Show or hide Gig View.",
        properties: &[p!("shown", Kind::Boolean)],
        distinct_arguments: &[],
        gateway_arguments: &[("shown", "shown")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "select_mode_slot",
        rpc: "device.selectModeSlot",
        classification: Classification::LiveWrite,
        description: "Select device-configured performance Mode Slot A, B, or C.",
        properties: &[
            p!(
                "slot",
                Kind::Integer {
                    min: 0,
                    max: Some(2)
                }
            ),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("slot", "slot"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_master_volume",
        rpc: "device.setMasterVolume",
        classification: Classification::RiskyWrite,
        description: "Set master output volume after explicit user confirmation and stale-value validation.",
        properties: &[
            p!(
                "value",
                Kind::Integer {
                    min: 0,
                    max: Some(100)
                }
            ),
            p!(
                "expected_value",
                Kind::Integer {
                    min: 0,
                    max: Some(100)
                }
            ),
            p!("confirm_risky_operation", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("value", "value"), ("expected_value", "expectedValue")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "recall_preset",
        rpc: "device.recallPreset",
        classification: Classification::LiveWrite,
        description: "Immediately recall a preset by setlist key and position, guarded by the currently active setlist, preset name, and position.",
        properties: &[
            p!("setlist_key", Kind::String),
            p!("position", Kind::Integer { min: 0, max: None }),
            p!("expected_preset_name", Kind::String),
            p!("expected_position", Kind::Integer { min: 0, max: None }),
            p!("expected_setlist_key", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("setlist_key", "setlistKey"),
            ("position", "position"),
            ("expected_preset_name", "expectedPresetName"),
            ("expected_position", "expectedPosition"),
            ("expected_setlist_key", "expectedSetlistKey"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "reload_preset",
        rpc: "device.reloadPreset",
        classification: Classification::RiskyWrite,
        description: "Discard unsaved edits and reload the active preset after explicit host confirmation.",
        properties: &[
            p!("expected_preset_name", Kind::String),
            p!("expected_position", Kind::Integer { min: 0, max: None }),
            p!("confirm_risky_operation", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("expected_preset_name", "expectedPresetName"),
            ("expected_position", "expectedPosition"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_tempo",
        rpc: "device.setTempo",
        classification: Classification::LiveWrite,
        description: "Immediately set performance tempo from 40 through 240 BPM.",
        properties: &[
            p!(
                "bpm",
                Kind::Integer {
                    min: 40,
                    max: Some(240)
                }
            ),
            p!(
                "expected_tempo",
                Kind::Integer {
                    min: 40,
                    max: Some(240)
                }
            ),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("bpm", "bpm"),
            ("expected_tempo", "expectedTempo"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_bypass",
        rpc: "device.toggleBypass",
        classification: Classification::LiveWrite,
        description: "Immediately enable or bypass one Grid block and verify device readback.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!(
                "column",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!("desired_bypassed", Kind::Boolean),
            p!("expected_bypassed", Kind::Boolean),
            p!(
                "expected_scene",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("column", "column"),
            ("desired_bypassed", "desiredBypassed"),
            ("expected_bypassed", "expectedBypassed"),
            ("expected_scene", "expectedScene"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_parameter",
        rpc: "device.setParameter",
        classification: Classification::LiveWrite,
        description: "Immediately set a writable block, splitter, or mixer parameter and verify it.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!(
                "column",
                Kind::Integer {
                    min: 0,
                    max: Some(9)
                }
            ),
            p!("parameter_index", Kind::Integer { min: 0, max: None }),
            p!(
                "value",
                Kind::Number {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "expected_value",
                Kind::Number {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "expected_scene",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("column", "column"),
            ("parameter_index", "parameterIndex"),
            ("value", "value"),
            ("expected_value", "expectedValue"),
            ("expected_scene", "expectedScene"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_parameter_scene_mode",
        rpc: "device.setParameterSceneMode",
        classification: Classification::LiveWrite,
        description: "Enable or disable per-scene storage for a block, splitter, or mixer parameter and verify device readback.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!(
                "column",
                Kind::Integer {
                    min: 0,
                    max: Some(9)
                }
            ),
            p!("parameter_index", Kind::Integer { min: 0, max: None }),
            p!("enabled", Kind::Boolean),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("column", "column"),
            ("parameter_index", "parameterIndex"),
            ("enabled", "enabled"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_parameter_expression",
        rpc: "device.setParameterExpression",
        classification: Classification::LiveWrite,
        description: "Assign EXP 1 or EXP 2 to a block, splitter, or mixer parameter, or clear it with pedal 0, preserving the requested heel and toe range.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!(
                "column",
                Kind::Integer {
                    min: 0,
                    max: Some(9)
                }
            ),
            p!("parameter_index", Kind::Integer { min: 0, max: None }),
            p!(
                "pedal",
                Kind::Integer {
                    min: 0,
                    max: Some(2)
                }
            ),
            p!(
                "minimum",
                Kind::Number {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "maximum",
                Kind::Number {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("column", "column"),
            ("parameter_index", "parameterIndex"),
            ("pedal", "pedal"),
            ("minimum", "minimum"),
            ("maximum", "maximum"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_lane_control_parameter",
        rpc: "device.setLaneControlParameter",
        classification: Classification::LiveWrite,
        description: "Set an Input Gate or Lane Output parameter with stale-value and preset guards.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!("control", Kind::StringEnum(&["inputGate", "laneOutput"])),
            p!("parameter_index", Kind::Integer { min: 0, max: None }),
            p!(
                "value",
                Kind::Number {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "expected_value",
                Kind::Number {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("control", "control"),
            ("parameter_index", "parameterIndex"),
            ("value", "value"),
            ("expected_value", "expectedValue"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_lane_control_scene_mode",
        rpc: "device.setLaneControlSceneMode",
        classification: Classification::LiveWrite,
        description: "Enable or disable per-scene storage for an Input Gate or Lane Output parameter and verify readback.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!("control", Kind::StringEnum(&["inputGate", "laneOutput"])),
            p!("parameter_index", Kind::Integer { min: 0, max: None }),
            p!("enabled", Kind::Boolean),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("control", "control"),
            ("parameter_index", "parameterIndex"),
            ("enabled", "enabled"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_expression_bypass",
        rpc: "device.setExpressionBypass",
        classification: Classification::LiveWrite,
        description: "Assign EXP 1 or EXP 2 to a block bypass with the QC switch mode, inversion, delay and latch-emulation settings.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!(
                "column",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!(
                "pedal",
                Kind::Integer {
                    min: 1,
                    max: Some(2)
                }
            ),
            p!(
                "mode",
                Kind::Integer {
                    min: 0,
                    max: Some(2)
                }
            ),
            p!("invert", Kind::Boolean),
            p!(
                "delay_ms",
                Kind::Integer {
                    min: 0,
                    max: Some(5000)
                }
            ),
            p!("latch_emulation", Kind::Boolean),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("column", "column"),
            ("pedal", "pedal"),
            ("mode", "mode"),
            ("invert", "invert"),
            ("delay_ms", "delayMs"),
            ("latch_emulation", "latchEmulation"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "move_block",
        rpc: "device.moveBlock",
        classification: Classification::LiveWrite,
        description: "Move an existing Grid block to an empty column in the same row with model and preset guards.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!(
                "from_column",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!(
                "to_column",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!("expected_model_id", Kind::Integer { min: 0, max: None }),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("from_column", "fromColumn"),
            ("to_column", "toColumn"),
            ("expected_model_id", "expectedModelId"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "add_block",
        rpc: "device.addBlock",
        classification: Classification::LiveWrite,
        description: "Add an installed model to an empty Grid cell and verify the resulting block.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!(
                "column",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!("model_id", Kind::Integer { min: 1, max: None }),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("column", "column"),
            ("model_id", "modelId"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "remove_block",
        rpc: "device.removeBlock",
        classification: Classification::LiveWrite,
        description: "Remove a Grid block after validating its model and active preset.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!(
                "column",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!("expected_model_id", Kind::Integer { min: 0, max: None }),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("column", "column"),
            ("expected_model_id", "expectedModelId"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_block_footswitch",
        rpc: "device.setBlockFootswitch",
        classification: Classification::LiveWrite,
        description: "Assign or clear a Grid block footswitch with preset, model and assignment guards.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!(
                "column",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!(
                "footswitch",
                Kind::NullableInteger {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!(
                "expected_footswitch",
                Kind::NullableInteger {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!("expected_model_id", Kind::Integer { min: 0, max: None }),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("column", "column"),
            ("footswitch", "footswitch"),
            ("expected_footswitch", "expectedFootswitch"),
            ("expected_model_id", "expectedModelId"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_stomp_momentary",
        rpc: "device.setStompMomentary",
        classification: Classification::LiveWrite,
        description: "Set a single-block STOMP footswitch to momentary or latching behavior and verify device readback.",
        properties: &[
            p!("footswitch", Kind::Integer { min: 0, max: None }),
            p!("momentary", Kind::Boolean),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("footswitch", "footswitch"),
            ("momentary", "momentary"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_stomp_label",
        rpc: "device.setStompLabel",
        classification: Classification::LiveWrite,
        description: "Set the visible label of a STOMP footswitch using the device's correct single- or multi-assignment storage.",
        properties: &[
            p!("footswitch", Kind::Integer { min: 0, max: None }),
            p!("label", Kind::VisibleString { max_chars: 32 }),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("footswitch", "footswitch"),
            ("label", "label"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_midi_out",
        rpc: "device.setMidiOut",
        classification: Classification::LiveWrite,
        description: "Replace up to 12 MIDI Out messages for a footswitch or expression-pedal source in the current preset.",
        properties: &[
            p!(
                "source",
                Kind::Integer {
                    min: 0,
                    max: Some(9)
                }
            ),
            p!("messages", Kind::MidiMessages),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("source", "source"),
            ("messages", "messages"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_preset_load_midi_out",
        rpc: "device.setPresetLoadMidiOut",
        classification: Classification::LiveWrite,
        description: "Replace the MIDI Out messages sent when the current preset loads.",
        properties: &[
            p!("messages", Kind::MidiMessages),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("messages", "messages"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_chain_input",
        rpc: "device.setChainInput",
        classification: Classification::LiveWrite,
        description: "Change a signal-row input after validating the current route and preset.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!("input_id", Kind::Integer { min: 0, max: None }),
            p!("expected_input_id", Kind::Integer { min: 0, max: None }),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("input_id", "inputId"),
            ("expected_input_id", "expectedInputId"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_chain_output",
        rpc: "device.setChainOutput",
        classification: Classification::LiveWrite,
        description: "Change a signal-row output after validating the current route and preset.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!("output_id", Kind::Integer { min: 0, max: None }),
            p!("expected_output_id", Kind::Integer { min: 0, max: None }),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("output_id", "outputId"),
            ("expected_output_id", "expectedOutputId"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_chain_split",
        rpc: "device.setChainSplit",
        classification: Classification::LiveWrite,
        description: "Set or clear a signal-row split and rejoin with complete stale-route guards.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!(
                "split_column",
                Kind::NullableInteger {
                    min: -1,
                    max: Some(7)
                }
            ),
            p!(
                "mix_column",
                Kind::NullableInteger {
                    min: -1,
                    max: Some(7)
                }
            ),
            p!(
                "expected_split_column",
                Kind::NullableInteger {
                    min: -1,
                    max: Some(7)
                }
            ),
            p!(
                "expected_mix_column",
                Kind::NullableInteger {
                    min: -1,
                    max: Some(7)
                }
            ),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("split_column", "splitColumn"),
            ("mix_column", "mixColumn"),
            ("expected_split_column", "expectedSplitColumn"),
            ("expected_mix_column", "expectedMixColumn"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_split_mute",
        rpc: "device.setSplitMute",
        classification: Classification::LiveWrite,
        description: "Mute or unmute a splitter/mixer path globally across scenes with exact device readback.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!("muted", Kind::Boolean),
            p!("expected_muted", Kind::Boolean),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("muted", "muted"),
            ("expected_muted", "expectedMuted"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "save_preset_as",
        rpc: "device.savePresetAs",
        classification: Classification::PersistentWrite,
        description: "Save the current preset to a reviewed device slot with explicit overwrite confirmation.",
        properties: &[
            p!("setlist_key", Kind::String),
            p!("position", Kind::Integer { min: 0, max: None }),
            p!("name", Kind::String),
            p!("expected_preset_name", Kind::String),
            p!("expected_position", Kind::Integer { min: 0, max: None }),
            p!("confirm_overwrite", Kind::Boolean),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("setlist_key", "setlistKey"),
            ("position", "position"),
            ("name", "name"),
            ("expected_preset_name", "expectedPresetName"),
            ("expected_position", "expectedPosition"),
            ("confirm_overwrite", "confirmOverwrite"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "rename_current_preset",
        rpc: "device.renameCurrentPreset",
        classification: Classification::PersistentWrite,
        description: "Rename the active stored preset after explicit confirmation.",
        properties: &[
            p!("new_name", Kind::String),
            p!("expected_preset_name", Kind::String),
            p!("expected_position", Kind::Integer { min: 0, max: None }),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("new_name", "name"),
            ("expected_preset_name", "expectedPresetName"),
            ("expected_position", "expectedPosition"),
        ],
        gateway_true_arguments: &["confirmRename"],
    },
    ActionSpec {
        name: "copy_preset",
        rpc: "device.copyPreset",
        classification: Classification::PersistentWrite,
        description: "Copy a device preset to a reviewed destination with explicit overwrite confirmation.",
        properties: &[
            p!("source_setlist_key", Kind::String),
            p!("source_position", Kind::Integer { min: 0, max: None }),
            p!("source_name", Kind::String),
            p!("destination_setlist_key", Kind::String),
            p!("destination_position", Kind::Integer { min: 0, max: None }),
            p!("expected_preset_name", Kind::String),
            p!("expected_position", Kind::Integer { min: 0, max: None }),
            p!("confirm_overwrite", Kind::Boolean),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("source_setlist_key", "sourceSetlistKey"),
            ("source_position", "sourcePosition"),
            ("source_name", "sourceName"),
            ("destination_setlist_key", "destinationSetlistKey"),
            ("destination_position", "destinationPosition"),
            ("expected_preset_name", "expectedPresetName"),
            ("expected_position", "expectedPosition"),
            ("confirm_overwrite", "confirmOverwrite"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_general_settings",
        rpc: "device.generalSettings",
        classification: Classification::Read,
        description: "Read the QC Device Settings and System settings without changing them.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_io_settings",
        rpc: "device.ioSettings",
        classification: Classification::Read,
        description: "Read complete input, output, headphone, USB, MIDI, expression-pedal, connection, and output-pairing settings.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_input_port",
        rpc: "device.setInputPort",
        classification: Classification::PersistentWrite,
        description: "Change one or more settings for a QC input. Each supplied field is sent in its own hardware update; input gain is expressed safely in dB.",
        properties: &[
            p!(
                "input_port_id",
                Kind::Integer {
                    min: 1,
                    max: Some(14)
                }
            ),
            p!(
                "level_db",
                Kind::NullableNumber {
                    min: -12.0,
                    max: Some(60.0)
                }
            ),
            p!(
                "impedance",
                Kind::NullableNumber {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "input_type",
                Kind::NullableNumber {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "ground_lift",
                Kind::NullableNumber {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("input_port_id", "inputPortId"),
            ("level_db", "levelDb"),
            ("impedance", "impedance"),
            ("input_type", "inputType"),
            ("ground_lift", "groundLift"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_output_port",
        rpc: "device.setOutputPort",
        classification: Classification::PersistentWrite,
        description: "Change level, ground lift, or mute for one QC output. Every supplied field is sent in a separate hardware update.",
        properties: &[
            p!(
                "output_port_id",
                Kind::Integer {
                    min: 1,
                    max: Some(22)
                }
            ),
            p!(
                "level",
                Kind::NullableNumber {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "ground_lift",
                Kind::NullableNumber {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!("mute", Kind::NullableBoolean),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("output_port_id", "outputPortId"),
            ("level", "level"),
            ("ground_lift", "groundLift"),
            ("mute", "mute"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_usb_port",
        rpc: "device.setUsbPort",
        classification: Classification::PersistentWrite,
        description: "Change USB level, headphone source, or dry/wet routing using normalized device values and separate hardware updates.",
        properties: &[
            p!(
                "level",
                Kind::NullableNumber {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "headphones_source",
                Kind::NullableNumber {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "dry_wet",
                Kind::NullableNumber {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("level", "level"),
            ("headphones_source", "headphonesSource"),
            ("dry_wet", "dryWet"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_midi_thru",
        rpc: "device.setMidiThru",
        classification: Classification::PersistentWrite,
        description: "Enable or disable the QC MIDI Thru setting after explicit confirmation.",
        properties: &[
            p!("enabled", Kind::Boolean),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("enabled", "enabled")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_output_pairing",
        rpc: "device.setOutputPairing",
        classification: Classification::PersistentWrite,
        description: "Pair or unpair output couples. Null leaves that output couple unchanged.",
        properties: &[
            p!("xlr12_linked", Kind::NullableBoolean),
            p!("out34_linked", Kind::NullableBoolean),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("xlr12_linked", "xlr12Linked"),
            ("out34_linked", "out34Linked"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_global_eq",
        rpc: "device.globalEq",
        classification: Classification::Read,
        description: "Read Global EQ bypass state and all 28 normalized parameters.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_global_eq_bypassed",
        rpc: "device.setGlobalEqBypassed",
        classification: Classification::PersistentWrite,
        description: "Enable or bypass the global EQ after explicit confirmation.",
        properties: &[
            p!("bypassed", Kind::Boolean),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("bypassed", "bypassed")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_global_eq_band",
        rpc: "device.setGlobalEqBand",
        classification: Classification::PersistentWrite,
        description: "Update one Global EQ band with sparse normalized controls after explicit confirmation.",
        properties: &[
            p!(
                "band",
                Kind::Integer {
                    min: 1,
                    max: Some(5)
                }
            ),
            p!(
                "gain",
                Kind::NullableNumber {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "frequency",
                Kind::NullableNumber {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "q",
                Kind::NullableNumber {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "filter_type",
                Kind::NullableInteger {
                    min: 0,
                    max: Some(4)
                }
            ),
            p!("enabled", Kind::NullableBoolean),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("band", "band"),
            ("gain", "gain"),
            ("frequency", "frequency"),
            ("q", "q"),
            ("filter_type", "filterType"),
            ("enabled", "enabled"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_global_eq_output",
        rpc: "device.setGlobalEqOutput",
        classification: Classification::PersistentWrite,
        description: "Update Global EQ output level and output-pair assignments after explicit confirmation.",
        properties: &[
            p!(
                "level",
                Kind::NullableNumber {
                    min: 0.0,
                    max: Some(1.0)
                }
            ),
            p!("out12", Kind::NullableBoolean),
            p!("out34", Kind::NullableBoolean),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("level", "level"), ("out12", "out12"), ("out34", "out34")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_mode_cycle",
        rpc: "device.modeCycle",
        classification: Classification::Read,
        description: "Read the configured footswitch modes in cycle order.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_mode_cycle",
        rpc: "device.setModeCycle",
        classification: Classification::PersistentWrite,
        description: "Replace the ordered footswitch mode cycle after explicit confirmation.",
        properties: &[
            p!(
                "slots",
                Kind::IntegerArray {
                    min: 0,
                    max: 8,
                    min_items: 1,
                    max_items: 3,
                    unique: true
                }
            ),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("slots", "slots")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_global_tempo_settings",
        rpc: "device.globalTempoSettings",
        classification: Classification::Read,
        description: "Read the device-global tempo block, including PRESET/GLOBAL mode, metronome options, routing, and all thirteen beat cells.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_tempo_metronome",
        rpc: "device.setTempoMetronome",
        classification: Classification::PersistentWrite,
        description: "Change named fields of the loaded preset's tempo/metronome block. Null leaves a field unchanged; time signature is applied before beat cells.",
        properties: &[
            p!("led_enabled", Kind::NullableBoolean),
            p!(
                "volume_db",
                Kind::NullableNumber {
                    min: -60.0,
                    max: Some(9.0)
                }
            ),
            p!("running", Kind::NullableBoolean),
            p!(
                "pan",
                Kind::NullableNumber {
                    min: -1.0,
                    max: Some(1.0)
                }
            ),
            p!(
                "time_signature",
                Kind::NullableStringEnum(&[
                    "2/4",
                    "3/4",
                    "4/4",
                    "5/4",
                    "6/4",
                    "7/4",
                    "8/4",
                    "9/4",
                    "10/4",
                    "11/4",
                    "12/4",
                    "13/4",
                    "3/8",
                    "6/8",
                    "9/8",
                    "12/8",
                    "5/8 (3+2)",
                    "5/8 (2+3)",
                    "7/8 (3+2+2)",
                    "7/8 (2+3+2)",
                    "7/8 (2+2+3)"
                ])
            ),
            p!(
                "subdivision",
                Kind::NullableStringEnum(&["1/4", "1/8", "1/8T", "1/16"])
            ),
            p!(
                "sound",
                Kind::NullableStringEnum(&[
                    "BLIP", "BLOCK", "COWBELL", "DIGITAL", "DRUM KIT", "SOFT KIT"
                ])
            ),
            p!(
                "routing",
                Kind::NullableStringEnum(&["MULTI", "HP", "OUT 1/2", "OUT 3/4", "SEND 1/2"])
            ),
            p!(
                "beats",
                Kind::NullableStringArray {
                    max_items: 13,
                    values: &["OFF", "MUTE", "DOWN", "ON"]
                }
            ),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("led_enabled", "ledEnabled"),
            ("volume_db", "volumeDb"),
            ("running", "running"),
            ("pan", "pan"),
            ("time_signature", "timeSignature"),
            ("subdivision", "subdivision"),
            ("sound", "sound"),
            ("routing", "routing"),
            ("beats", "beats"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_tempo_mode",
        rpc: "device.setTempoMode",
        classification: Classification::PersistentWrite,
        description: "Select whether the Quad Cortex uses the loaded preset tempo or its device-global tempo block.",
        properties: &[
            p!("mode", Kind::StringEnum(&["PRESET", "GLOBAL"])),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("mode", "mode")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "get_looper_status",
        rpc: "device.looperStatus",
        classification: Classification::Read,
        description: "Read the complete Looper X transport and progress state when a looper is present.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "control_looper",
        rpc: "device.controlLooper",
        classification: Classification::LiveWrite,
        description: "Control Looper X through its documented MIDI CC interface.",
        properties: &[
            p!(
                "command",
                Kind::StringEnum(&[
                    "open",
                    "close",
                    "duplicate",
                    "oneShot",
                    "halfSpeed",
                    "punch",
                    "record",
                    "play",
                    "reverse",
                    "undoRedo",
                    "duplicateMode",
                    "quantize",
                    "midiClockStart",
                    "performMode",
                    "routingMode"
                ])
            ),
            p!(
                "value",
                Kind::NullableInteger {
                    min: 0,
                    max: Some(13)
                }
            ),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("command", "command"), ("value", "value")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "list_recents",
        rpc: "device.recents",
        classification: Classification::Read,
        description: "List recently used presets with authoritative folder metadata.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "list_favorites",
        rpc: "device.favorites",
        classification: Classification::Read,
        description: "List favorite presets using request correlation even when the reply omits its favorites flag.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_favorite",
        rpc: "device.setFavorite",
        classification: Classification::PersistentWrite,
        description: "Add or remove one exact device library entry from Favorites after explicit confirmation.",
        properties: &[
            p!("name", Kind::String),
            p!("folder_key", Kind::String),
            p!("folder_name", Kind::String),
            p!("is_factory", Kind::Boolean),
            p!("favorite", Kind::Boolean),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("name", "name"),
            ("folder_key", "folderKey"),
            ("folder_name", "folderName"),
            ("is_factory", "isFactory"),
            ("favorite", "favorite"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "list_pinned_models",
        rpc: "device.pinnedModels",
        classification: Classification::Read,
        description: "List model IDs and capture keys pinned in the device model browser.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_model_pinned",
        rpc: "device.setModelPinned",
        classification: Classification::PersistentWrite,
        description: "Pin or unpin one model ID after explicit confirmation.",
        properties: &[
            p!("model_id", Kind::Integer { min: 1, max: None }),
            p!("pinned", Kind::Boolean),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("model_id", "modelId"), ("pinned", "pinned")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "list_captures",
        rpc: "device.captures",
        classification: Classification::Read,
        description: "List loadable Neural Captures with their content keys and names.",
        properties: &[],
        distinct_arguments: &[],
        gateway_arguments: &[],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "load_capture",
        rpc: "device.loadCapture",
        classification: Classification::LiveWrite,
        description: "Place or retarget a Neural Capture block using a device library key and name, guarded by the current Grid cell and preset.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!(
                "column",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!("key", Kind::String),
            p!("name", Kind::String),
            p!("model_id", Kind::NullableInteger { min: 1, max: None }),
            p!(
                "expected_model_id",
                Kind::NullableInteger { min: 0, max: None }
            ),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("column", "column"),
            ("key", "key"),
            ("name", "name"),
            ("model_id", "modelId"),
            ("expected_model_id", "expectedModelId"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "list_irs",
        rpc: "device.irs",
        classification: Classification::Read,
        description: "List loadable Impulse Responses from the whole library or a selected device folder.",
        properties: &[p!("folder", Kind::NullableString)],
        distinct_arguments: &[],
        gateway_arguments: &[("folder", "folder")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "load_ir",
        rpc: "device.loadIr",
        classification: Classification::LiveWrite,
        description: "Place or retarget an IR Loader and set one of its two IR slots by key and name, guarded by the current Grid cell and preset.",
        properties: &[
            p!(
                "row",
                Kind::Integer {
                    min: 0,
                    max: Some(3)
                }
            ),
            p!(
                "column",
                Kind::Integer {
                    min: 0,
                    max: Some(7)
                }
            ),
            p!("key", Kind::String),
            p!("name", Kind::String),
            p!(
                "slot",
                Kind::Integer {
                    min: 0,
                    max: Some(1)
                }
            ),
            p!("model_id", Kind::NullableInteger { min: 1, max: None }),
            p!(
                "expected_model_id",
                Kind::NullableInteger { min: 0, max: None }
            ),
            p!("expected_preset_name", Kind::String),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("row", "row"),
            ("column", "column"),
            ("key", "key"),
            ("name", "name"),
            ("slot", "slot"),
            ("model_id", "modelId"),
            ("expected_model_id", "expectedModelId"),
            ("expected_preset_name", "expectedPresetName"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "create_setlist",
        rpc: "device.createSetlist",
        classification: Classification::PersistentWrite,
        description: "Create a user setlist after explicit confirmation.",
        properties: &[
            p!("name", Kind::VisibleString { max_chars: 64 }),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("name", "name")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "delete_setlist",
        rpc: "device.deleteSetlist",
        classification: Classification::PersistentWrite,
        description: "Delete a named user setlist and its contents after explicit confirmation.",
        properties: &[
            p!("name", Kind::VisibleString { max_chars: 64 }),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("name", "name")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "duplicate_setlist",
        rpc: "device.duplicateSetlist",
        classification: Classification::PersistentWrite,
        description: "Create a user setlist and copy its source presets through the shared recall-and-save workflow after explicit confirmation.",
        properties: &[
            p!("source_setlist_key", Kind::String),
            p!("destination_name", Kind::VisibleString { max_chars: 64 }),
            p!(
                "limit",
                Kind::NullableInteger {
                    min: 0,
                    max: Some(256)
                }
            ),
            p!("expected_preset_name", Kind::String),
            p!(
                "expected_position",
                Kind::Integer {
                    min: 0,
                    max: Some(255)
                }
            ),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("source_setlist_key", "sourceSetlistKey"),
            ("destination_name", "destinationName"),
            ("limit", "limit"),
            ("expected_preset_name", "expectedPresetName"),
            ("expected_position", "expectedPosition"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "delete_preset",
        rpc: "device.deletePreset",
        classification: Classification::PersistentWrite,
        description: "Delete a named preset from a writable user setlist after explicit confirmation.",
        properties: &[
            p!("setlist_key", Kind::String),
            p!("name", Kind::String),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("setlist_key", "setlistKey"), ("name", "name")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "move_preset",
        rpc: "device.movePreset",
        classification: Classification::PersistentWrite,
        description: "Move a named preset to another slot in its user setlist after explicit confirmation.",
        properties: &[
            p!("setlist_key", Kind::String),
            p!("name", Kind::String),
            p!(
                "position",
                Kind::Integer {
                    min: 0,
                    max: Some(255)
                }
            ),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("setlist_key", "setlistKey"),
            ("name", "name"),
            ("position", "position"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_general_integer",
        rpc: "device.setGeneralInteger",
        classification: Classification::PersistentWrite,
        description: "Change one validated integer Device Setting after explicit confirmation. Hold timing uses its wire index 0 through 5.",
        properties: &[
            p!(
                "setting",
                Kind::StringEnum(&[
                    "screenBrightness",
                    "ledBrightness",
                    "dimmedLedBrightness",
                    "holdTiming",
                    "midiChannel"
                ])
            ),
            p!(
                "value",
                Kind::Integer {
                    min: 0,
                    max: Some(100)
                }
            ),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("setting", "setting"), ("value", "value")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_general_toggle",
        rpc: "device.setGeneralToggle",
        classification: Classification::PersistentWrite,
        description: "Change one validated on/off Device Setting after explicit confirmation.",
        properties: &[
            p!(
                "setting",
                Kind::StringEnum(&[
                    "midiOverUsb",
                    "ignoreDuplicatePc",
                    "stompModeAutoAssign",
                    "swapTempoTunerAccess",
                    "disableInternetConnectionCheck",
                    "dynamicDelayCompensation",
                    "presetDimmed",
                    "midiClockIn",
                    "gigViewStompAccess"
                ])
            ),
            p!("enabled", Kind::Boolean),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("setting", "setting"), ("enabled", "enabled")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_scene_bypass_behavior",
        rpc: "device.setSceneBypassBehavior",
        classification: Classification::PersistentWrite,
        description: "Change the global scene block-bypass persistence behavior after explicit confirmation.",
        properties: &[
            p!(
                "behavior",
                Kind::StringEnum(&["alwaysOverwrite", "nonstompOverwrite", "neverOverwrite"])
            ),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("behavior", "behavior")],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_master_volume_assignment",
        rpc: "device.setMasterVolumeAssignment",
        classification: Classification::PersistentWrite,
        description: "Replace all four Master Volume output assignments atomically after explicit confirmation.",
        properties: &[
            p!("out12", Kind::Boolean),
            p!("out34", Kind::Boolean),
            p!("send12", Kind::Boolean),
            p!("headphones", Kind::Boolean),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[
            ("out12", "out12"),
            ("out34", "out34"),
            ("send12", "send12"),
            ("headphones", "headphones"),
        ],
        gateway_true_arguments: &[],
    },
    ActionSpec {
        name: "set_global_bypass",
        rpc: "device.setGlobalBypass",
        classification: Classification::PersistentWrite,
        description: "Replace all Cab and IR global-bypass row flags atomically after explicit confirmation.",
        properties: &[
            p!("cab", Kind::BooleanRows),
            p!("ir", Kind::BooleanRows),
            p!("confirm_persistent_write", Kind::Boolean),
        ],
        distinct_arguments: &[],
        gateway_arguments: &[("cab", "cab"), ("ir", "ir")],
        gateway_true_arguments: &[],
    },
];
